### ISSUE TITLE
Scores don't show submissions currently undergoing manual assessment at all

### ISSUE THREAD

**Issue by MaisiKoleni** [ls1intum/Artemis#2765] opened 2021-01-27 18:48 UTC
The Scores of a programming exercise only show submissions that are:
 - either still completely automatic
 - or manual and submitted (in this case even with evaluated complaint)

As instructor, I rely on the scores table to show me always the most recent finished result, which could be "Build After Due Date" or manual and already submitted. It is in my eyes very bad considering our workflows, expectations as long-time users and previous behavior to hide submissions completely while tutors are working on them. We expect to find all relevant information about a student's participation in the scores table, be it completion date, latest completed result,  assessment type, repository, build plan + logs or the assessment, or even all individual submissions of a student.

The exercise below is the same as the one in my first comment in #2760 and all invisible assessments are the ones locked, but not completed by `artemis_test_user_7`:
![image](https://user-images.githubusercontent.com/11130248/106037421-f1260280-60d6-11eb-8d9c-559416fa151c.png)

If anything, I would recommend showing the status "currently being assessed by a tutor" in a different, more subtle way but keeping all submissions that have **any** result in the table.

Version is the one from `2021-01-27 17:14`, pre-`4.9.3`

**Comment by krusche** [comment] 2021-01-27 20:11
I'm sorry but I don't understand what the issue is. The description of the problem is missing!

Please describe the exact problem in a reproducible way and the exact expected behavior in detail.

**Comment by krusche** [comment] 2021-01-27 20:49
We just investigated this, and the scores page never showed unfinished results until now, so I'll close this issue!

**Closed by krusche** 2021-01-27 20:49 UTC
Labels: bug, component:Programming, priority:high
