### ISSUE TITLE
Submissions are stored twice

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#4267] opened 2021-11-07 17:18 UTC
### Describe the bug

The submissions are stored twice for some students. So they have the same id, commit hash and so on. But the results are only stored in the first of the clones.
The student can also not see a result because of this bug, since Artemis tries to fetch a result from the clone without results.

### To Reproduce

I currently don't really know when or why the submissions get duplicated, but it happens sometimes...

### Expected behavior

No duplicated submissions

### Screenshots

![Bildschirmfoto 2021-11-07 um 18 15 36](https://user-images.githubusercontent.com/38322605/140654890-8d8ac827-b840-46f1-9597-09db78b21b88.png)

### What browsers are you seeing the problem on?

Safari

**Comment by krusche** [comment] 2021-11-07 17:49
Duplicate of #4257

**Closed by krusche** 2021-11-07 17:49 UTC
Labels: bug, component:Programming
