### ISSUE TITLE
Cannot get link to clone using SSH

### ISSUE THREAD

**Issue by Jojaa350** [ls1intum/Artemis#2777] opened 2021-01-29 11:25 UTC
### Describe the bug
When trying to clone a repository, a link starting with 'https://'... is shown although the button on the right shows "Use HTTPS". Pressing the "Use HTTPS" / "Use SSH"-Button does not change the link.

#### To Reproduce

1. Use the "Clone Repository" Button on any exercise of any course.
2. Activate the "Use HTTPS" / "Use SSH"-Button.
3. The link doesn't change.

#### Expected behavior
Getting the link to clone using SSH upon pressing "Use SSH".

#### Screenshots
With SSH enabled:
![With SSH](https://i.ibb.co/XX75JJz/Anmerkung-2021-01-29-121316.png)

With HTTPS enabled:
![With HTTPS](https://i.ibb.co/0Ckbm1X/Anmerkung-2021-01-29-121527.png)
### Environment

<details><pre>
 - OS: Windows 10
 - Browser: Both Firefox 84.0.2 and Chromium 86.0.4204.0
 - Version: Artemis 4.9.3
</pre></details>

#### Output in Web Console

<details><pre>
  No output on the Web Console.
</pre></details>

**Comment by just-max** [comment] 2021-01-29 14:18
Having the same issue. Workaround to get the SSH Link:
1. Copy the https Link from Artemis
2. Open it in the browser to get to BitBucket
3. Copy the SSH Link from the Clone button on the left

**Comment by krusche** [comment] 2021-02-01 08:00
Duplicate of #2776

**Closed by krusche** 2021-02-01 08:00 UTC
Labels: bug
