### ISSUE TITLE
`Programming Exercises`: Viewing the exercise details results in an internal server error for the diff-report route

### ISSUE THREAD

**Issue by maximiliansoelch** [ls1intum/Artemis#10029] opened 2024-12-16 15:08 UTC
### Describe the bug

When opening the exercise details of an exercise (that I just imported), I get an internal server error:
<img width="1507" alt="image" src="https://github.com/user-attachments/assets/c7470f64-f0dd-47b2-b5d3-eeae9a22b470" />

This is the corresponding Sentry issue: https://sentry.ase.in.tum.de/organizations/aet/issues/2192/?query=is%3Aunresolved&referrer=issue-stream&stream_index=2
So it looks like this issue was introduced with the latest release. Maybe a dependency update for jgit?

### To Reproduce

1. Click on a programming exercise
2. See the internal server error message at the top right 

### Expected behavior

The exercise details page should be displayed correctly.

### Screenshots

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/189c3da3-1624-4729-8599-0399d51da2f7" />

### Which version of Artemis are you seeing the problem on?

7.7.5

### What browsers are you seeing the problem on?

Safari

**Comment by krusche** [comment] 2024-12-16 19:54
I think the 500 Internel Server Error is specific to this particular programming exercise (Java). The details in the network tab reveal the following:
```
{
    "type": "https://www.jhipster.tech/problem/problem-with-message",
    "title": "Internal Server Error",
    "status": 500,
    "detail": "Name is null",
    "path": "/api/programming-exercises/15589/diff-report",
    "message": "error.http.500"
}
```

In any case, the rest of the page should be displayed normally, even when there is an error with one specific REST call.

**Comment by krusche** [comment] 2024-12-16 19:59
according to the stack trace on Sentry, this is an internal null pointer exception in JGit's `DiffFormatter`, I am not sure if we can fix this. Maybe, the exercise uses a Java feature, that the `DiffViewer` cannot handle? In any case, the programming exercise for which this error occurs is using Java 17. I'll try to find out more locally.

**Comment by krusche** [comment] 2024-12-16 20:16
seems to happen with `DiffEntry[MODIFY gradle/wrapper/gradle-wrapper.jar]`. This is a binary file and could be excluded from the diff

**Comment by krusche** [comment] 2024-12-16 23:27
Here is a branch that improves the error handling on the page so it gets rendered completely: `bugfix/diff-report-error-handling`

**Comment by magaupp** [comment] 2024-12-17 01:49
This seems to be a recent JGit bug which affects diff files with gitattribute `-diff` (or `binary`). This has been fixed in a recent commit: https://github.com/eclipse-jgit/jgit/commit/f2741cacec9f46724a0e48cc55cbb8892361e3d0. But there's no release yet.

**Comment by magaupp** [comment] 2024-12-17 08:09
I can confirm that the error with the recent dependency update of JGit: https://github.com/ls1intum/Artemis/commit/96ca4ec8bcbe508ba3d4ed247fdf57642146ba2d#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19L22

**Comment by maximiliansoelch** [comment] 2024-12-17 12:07
> I think the 500 Internel Server Error is specific to this particular programming exercise (Java). The details in the network tab reveal the following:
> 
> ```
> {
>     "type": "https://www.jhipster.tech/problem/problem-with-message",
>     "title": "Internal Server Error",
>     "status": 500,
>     "detail": "Name is null",
>     "path": "/api/programming-exercises/15589/diff-report",
>     "message": "error.http.500"
> }
> ```
> 
> In any case, the rest of the page should be displayed normally, even when there is an error with one specific REST call.

This is interesting because for the original exercise, from which I imported this exercise, the exercise details can be displayed 🤔

**Comment by magaupp** [comment] 2024-12-19 21:26
The JGit update has been reverted in https://github.com/ls1intum/Artemis/commit/3a6832e88ba1a3c5f44251d2f893d3bea89b1d0a.

**Closed by magaupp** 2024-12-19 21:26 UTC
Labels: bug, exercise, programming
