### ISSUE TITLE
[Exam] Copy/ Import existing exam 

### ISSUE THREAD

**Issue by JohannesWeiss** [ls1intum/Artemis#2845] opened 2021-02-09 11:36 UTC
### Is your feature request related to a problem?
Currently, exams always have to be created from scratch, although many parameters (such as exercises/ types, registered students, ...) may stay the same. This makes testing exam mode slower, as everything has to be set up over again, even though there may be little changes.

### Describe the solution you'd like
A button to re-use an existing exam and select some new parameters (mostly times/ dates) for import. The registered students and exercise groups with the exercises should stay the same. Then only student exams have to be generated to start testing. 

### Describe alternatives you've considered
Manually creating the exam and importing everything else (exercises) + registering students again. This is the current workflow while testing different exam features.

**Comment by ge65cer** [comment] 2022-10-18 18:32
Duplicate of https://github.com/ls1intum/Artemis/issues/3848

**Closed by ge65cer** 2022-10-18 18:32 UTC
Labels: feature, priority:low, exam mode
