### ISSUE TITLE
Test result reporting broken with Surefire 3.0-M4 and later

### ISSUE THREAD

**Issue by snowball77** [ls1intum/Artemis#2273] opened 2020-10-26 01:14 UTC
### Describe the bug
When running a student exercise with Maven Surefire, we ran into a regression. Starting from a reporting refactoring in Surefire at v3.0-M4, the message of the failure does not get reported any more in the XML output. We will file an issue on their side for this, as we think this is a bug in Surefire. However, this has consequences breaking Artemis. The non-existing message in the XML leads to a null message in the Json of the Artemis Jenkins plugin (v1.0). This again is picked up in Artemis as successful test run - despite the run being reported correctly as failure.

#### To Reproduce
1. Create a student exercise with Surefire >= 3.0-M4
2. Add failing tests to it
3. Run them via Artemis (either in a Student exercise instance or in the template repo)

#### Expected behavior
Even if no message gets passed, failed or errored tests should not be recorded as "success". I expect them to be recorded as "failed" or "error". The missing message might be replaced with a default warning message, stating that no message was received and an instructor should check the setup.

### Environment
<details><pre>
 - OS: macOS client, Ubuntu 20.04LTS server
 - Browser: Firefox
 - Version: latest dev
</pre></details>

#### Additional context
Java student exercise using Maven Surefire >= 3.0-M4 as test execution and reporting engine. Using JUnit-Platform (i.e. Junit 5 runner) as test engine

**Comment by snowball77** [comment] 2020-10-26 01:20
[TEST-de.unistuttgart.iste.rss.oo.hamstersimulator.test.ExampleTest.txt](https://github.com/ls1intum/Artemis/files/5436328/TEST-de.unistuttgart.iste.rss.oo.hamstersimulator.test.ExampleTest.txt)

Example of a surefire report lacking the message attribute

**Comment by snowball77** [comment] 2020-10-26 01:26
For the Jenkins variant of Artmis, I suggest changing the code in JenkinsService.java in addFeedbackToResult Method from
´´´
        // Extract test case feedback
        for (final var testSuite : report.getResults()) {
            for (final var testCase : testSuite.getTestCases()) {
                var errorMessage = Optional.ofNullable(testCase.getErrors()).map((errors) -> errors.get(0).getMessage());
                var failureMessage = Optional.ofNullable(testCase.getFailures()).map((failures) -> failures.get(0).getMessage());
                var errorList = errorMessage.or(() -> failureMessage).map(List::of).orElse(Collections.emptyList());

                result.addFeedback(feedbackService.createFeedbackFromTestCase(testCase.getName(), errorList, errorList.isEmpty(), programmingLanguage));
            }
        }
´´´
to not use an empty list as errorList as last result. I suggest using a default errorList if no message can be found but the testCase is failed or error. The default should contain a message informing the user of Artemis that either a message was not set in the test case or no message was transmitted from the test executor to Artemis. However, it should not be treated as success (see errorList.isEmpty()) query to define success.

**Comment by snowball77** [comment] 2020-10-26 01:29
As our hamster simulator relies on Java 14 and other newer things, for us the issue is a blocker (which is bad, 1 week before the start of the semester) as it breaks Artemis and we cannot downgrade surefire as JDK14 is supported only in newer versions. So, I would hope for making Artemis more robust in the first place while finding a (temporary) solution to the surefire issue.

**Comment by b-fein** [comment] 2020-10-26 10:12
In #2224 I already implemented the change to the JenkinsService fixing the problem that tests with failures but no message attributes are marked as success.
https://github.com/ls1intum/Artemis/pull/2224/files#diff-a7b1aad7f5dfbc746b1babaa8eda080d429d5c6bcdb126450d84542a10287c2d

If no message is present, it tries to generate one from the type of error (= name of the exception thrown).

**Comment by krusche** [comment] 2020-10-26 10:31
This is one of the reasons why we have not yet supported Junit 5. There are some changes in the surefire report plugin that prevent the structural tests of the Java template to work correctly. I already tried this out a year ago or so.

Also, I don't like that they use milestone versions for several years :-( 

Please note, that using non official releases is something that we cannot promise to support, as it might be very time consuming and we have limited resources

I think @MaisiKoleni is already working on a solution to support Junit 5 as part of the integration of AJTS into the java exercise template.

For now, I would recommend to use Junit 4 (if possible) with the surefire version in the exercise template

**Comment by snowball77** [comment] 2020-10-26 12:14
@krusche I fully agree, surefire is not so well-maintained. However, we need it due to the dependency on JDK14. I would rank the -M releases in surefire as releases - otherwise you have to rely on very old stuff. 
Also no problem with the man power. We are happy to help and submit merge requests. My students and I analysed all the code related to this issue for days, we can at least do the work and propose improvements/fixes. Still I usually start by filing and issue. Internally we have already worked on patches for surefire. 

I have to ask my students whether Junit 4 is an option, but still the 3.0-Mx surefires will be needed due to the JDK needed. And we cannot revert the hamster simulator back, this would be infeasible :-)

**Comment by snowball77** [comment] 2020-10-26 12:17
@b-fein Great to read this. I assume this might already fix this issue - as I only demanded to make it more robost in Artemis. Not a full support fix.

Maybe it is an option to use the body text of the XML message in the Issue Exporter Plugin in Jenkins, in case no explicit message is given. At least this text contains the actual message as part of the text - as you can see in my example XML. Would it be worthwhile suggesting this improvement to the Jenkins Build Result Exporter Plugin? This should be rather easy to implement also for my students.

**Comment by MaisiKoleni** [comment] 2020-10-26 13:08
Why exactly is the newer surefire needed for Java 14? Otherwise, it is still possible to use both JUnit 4 and 5 via the vintage test engine, although this can get a bit messy. It also depends on whether you need the structural tests or not. I was also able to make the structural tests work in Artemis with JUnit 5, just the test method names are only numbered so far.

**Comment by MaisiKoleni** [comment] 2020-10-26 13:10
At least I have used JUnit 5 without problems so far with Java 13 and 14 exercises (but without structural tests).

**Comment by snowball77** [comment] 2020-10-26 13:15
@MaisiKoleni According to the surefire changelog, Java Modules work with surefire and JDK 9 or 11 only from 3.0-M4 onwards. In case it is needed, my students can most likely give more details on this.

**Comment by snowball77** [comment] 2020-10-26 13:22
I assume this issue is a duplicate of #2244 which is further discussed in #2224 which most likely fixes the issue already. Maybe we can already close it? Or wait for #2224 for getting merged?

**Comment by MaisiKoleni** [comment] 2020-10-26 13:35
@snowball77 You are right that this can likely be an issue when modules are used. And you are right, the problem initially described in the issue is already known and fixed (as far as I know). But we can keep it open until the issue is resolved, I think.

**Comment by MaisiKoleni** [comment] 2020-10-26 13:35
BTW, I have just now found a way to run the structural tests with JUnit 5, and surefire 3.0.0-M5 in Java 15. It is kind of a workaround, but seems to fit well into Artemis.

**Comment by snowball77** [comment] 2020-10-26 13:47
@MaisiKoleni Would be interested in a patch or guidelines how to do it. But already with #2224 I assume we have a good chance to move forward here. So far, I guess my students have not configured structural tests.

**Comment by MaisiKoleni** [comment] 2020-10-26 13:54
It is planned to integrate that and migrate to JUnit 5 as fast as possible

**Comment by krusche** [comment] 2020-10-26 17:18
@MaisiKoleni thanks that you got Junit5 working. I am still a bit concerned with the surefire 3.0.0-M5 version (we should really tell them that one milestone release per year is bad practice!), that this could cause problems, especially if we offer this in the standard template of programming exercises in Artemis. So I would appreciate if we and you thoroughly test this, when the PR is available.

Regarding PR #2224: we can merge it, as soon as we have enough tests and approvals for the PR. 

@snowball77 Should we invite you and your students to the Artemis team on Github? So that they could participate more easily? We can also give you access to our test infrastructure, if this helps. If yes, please send me a list of Github accounts, names and emails to krusche@in.tum.de 
(Our organization requires everyone to write their full name, their affiliation and add a picture to their Github account)

We are currently short on PR reviewers and testers, so any help is appreciated :-)

**Comment by snowball77** [comment] 2020-10-27 09:31
We have filed a bug for surefire including some text to explain how to fix it. If you like you can help by upvoting the issue :-) https://issues.apache.org/jira/browse/SUREFIRE-1857

Internally we have now created and deployed a patched version of surefire. This also resolves the issue.

**Comment by krusche** [comment] 2020-10-29 16:07
@sleiss has also fixed this in the new Jenkins plugin 1.2.0: https://github.com/ls1intum/jenkins-server-notification-plugin
@MaisiKoleni will adapt Artemis to support the new format in #2281

**Closed** 2020-10-29 21:44 UTC
Labels: bug

**Comment by nk-coding** [comment] 2020-11-19 05:46
The pull request on surefire is now [merged](https://github.com/apache/maven-surefire/pull/324)  
The snapshot version (3.0.0-M6-SNAPSHOT) already include the fix, using snapshot versions is explained [here](https://maven.apache.org/guides/development/guide-testing-development-plugins.html)
