### ISSUE TITLE
Chat text in thread view does not update when switching threads

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#9803] opened 2024-11-17 14:10 UTC
### Describe the bug

When using the “Show X Replies” button in the Communication section to open threads, switching between threads does not update the displayed chat text in the thread view. Instead, the chat text from the first opened thread remains visible, which can lead to confusion.

### To Reproduce

1.	Go to the Communication section.
2.	Click on “Show X Replies” to open a thread.
3.	Switch to another thread using the same method.
4.	Observe that the chat text in the thread view does not update and still shows the content from the first opened thread.

### Expected behavior

The chat text in the thread view should update to display the correct content of the currently selected thread.

### Which version of Artemis are you seeing the problem on?

7.7.1

### What browsers are you seeing the problem on?

Chrome

**Comment by badkeyy** [comment] 2024-11-20 17:51
Duplicate of https://github.com/ls1intum/Artemis/issues/9754 - I am already working on this

**Comment by PaRangger** [comment] 2024-11-21 09:10
Closed due to being duplicate as @badkeyy described. 👍

**Closed by PaRangger** 2024-11-21 09:10 UTC
Labels: bug, component:Communication, communication
