### ISSUE TITLE
Can't view full model during Plagiarism check

### ISSUE THREAD

**Issue by TheTrueVester** [ls1intum/Artemis#5347] opened 2022-07-07 13:52 UTC
### Describe the bug

Whilst reviewing plagiarism cases, I noticed that I can't scroll down on models. Thus I'm not able to view the bottom half of some submissions. 

### To Reproduce

1. Go to Course management. 
2. Go to exercises. 
3. Select a modelling exercise that has submissions
4. Click on Check Plagiarism
5. Click Detect Plagiarism
6. Click on a case with a modelling submission that's taller than your screen.

### Expected behavior

Being able to scroll in order to see the rest of the model. Only horizontal scrolling is possible currently. Vertical would be appreciated.

### Screenshots

![image](https://user-images.githubusercontent.com/47668936/177991632-2ecf9d8b-7a92-4450-a0ea-f3b4ba6c037a.png)

### What browsers are you seeing the problem on?

Safari

**Comment by ge65cer** [comment] 2022-08-05 19:04
Duplicate of https://github.com/ls1intum/Artemis/issues/5402

**Closed by ge65cer** 2022-08-05 19:04 UTC
Labels: bug, duplicate, plagiarism detection
