### ISSUE TITLE
Mouse wheel opening new tab with exercise or right click to open new tabs 

### ISSUE THREAD

**Issue by D0MI-1** [ls1intum/Artemis#4406] opened 2021-11-30 16:48 UTC
### Is your feature request related to a problem?

I'm always frustrated when I have to remember that Artemis is not even supporting simple stuff from every side since 2001 to open new tabs for every exercise. Artemis needs my left click for this so I will always do one task finish it and then go back to the best list view i could ever imagin to search again where I was what my next task is and where I am (or who I am).

### Describe the solution you'd like

Add my request asap

### Additional context

![grafik](https://user-images.githubusercontent.com/62054091/144090332-e2cfc12e-66fa-4bca-8087-820986851366.png)

**Comment by Strohgelaender** [comment] 2021-11-30 17:16
Duplicate of #2820?

**Comment by krusche** [comment] 2021-11-30 17:21
I suggest you formulate your feature request a bit more respectfully! It's frustrating to developers to read your test!

**Closed by krusche** 2021-11-30 17:21 UTC
Labels: feature
