### ISSUE TITLE
Course Management View Permission Bug as Tutor User

### ISSUE THREAD

**Issue by Ceiridge** [ls1intum/Artemis#7797] opened 2023-12-15 04:30 UTC
### Describe the bug

When clicking on `Manage` in a course, whereas the user is a tutor (not an instructor), a permission error appears, although the course management page can be viewed.
This happens in production in the ITP course and it did not happen with extended permissions (for example a user that can view all exams).

### To Reproduce

1. Log in as a tutor user
2. Open a course normally, in which you are tutoring
3. Click on `Manage`

### Expected behavior

No permission error appears.

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/40047520/c73526be-0267-465f-bbdd-48a46bf0db36)

### Which version of Artemis are you seeing the problem on?

6.7.1

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

**Comment by b-fein** [comment] 2023-12-15 07:11
Duplicate of #7739.

Can you please check the browser console which API request actually fails? That would help tracking down the problematic one.

**Comment by Strohgelaender** [comment] 2023-12-15 08:45
Can you also Share if the ITP-Course uses some special settings? Is e.g. Iris active? Both issues are about this specific course.

**Comment by Ceiridge** [comment] 2023-12-15 16:55
@b-fein @Strohgelaender 
The following request fails `GET https://artemis.in.tum.de/api/courses/274/raw-iris-settings` with a JSON answer containing the following: `"You are not allowed to access the Course with id 274"`

So it's related to Iris, which is enabled.

**Closed** 2024-11-12 13:20 UTC
Labels: bug, small, component:Iris
