### ISSUE TITLE
"Open link in new tab" instead of "Back"

### ISSUE THREAD

**Issue by rgatuzov** [ls1intum/Artemis#1671] opened 2020-06-17 22:19 UTC
### Is your feature request related to a problem?
Yes

### Describe the solution you'd like
I'd like assignments to work like normal links, for a student to be able to open multiple assignments at once from one window.

### Additional context
As a student, I use artemis quite often and sometimes want to open, e.g., 3 exercises at once from 1 window (from 1 list of exercises), but I can't do it, so I have to open artemis 3 times in 3 different tabs and search for these assignments again. It's quite uncomfortable and I didn't find a way to open new tabs from the list.
![image](https://user-images.githubusercontent.com/65923908/84956394-6705cc80-b0f9-11ea-887b-e50abc3b2abf.png)

**Comment by julian-christl** [comment] 2020-06-17 22:28
Possible solution could be to implement it as a link to provide functionality via the context menu (at least for the buttons). Alternatively we could implement at least a functionality to open such things in a new tab with the middle mouse button (like possible with HTML-links).

**Comment by jpbernius** [comment] 2020-06-25 11:50
Thanks for requesting this feature. I am closing this, as it is essentially a dupe of #611.
Most navigation elements are implemented as a `<button>` and thereby do not support new tabs.

**Closed by jpbernius** 2020-06-25 11:50 UTC
Labels: duplicate, feature
