### ISSUE TITLE
Linking Lecture(-slides)/exercises not possible on lecture communication

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#7980] opened 2024-01-31 16:00 UTC
### Describe the bug

When trying to link a lecture slide in a message tothe lecture communication, it does nothing.

### To Reproduce

1. Lecture with a Attachment Unit containing a file (can be any lecture and any lecture unit as long as there is some PDF to take the slide from somewhere.
2. Click on "New message" on the right in the communication's tab
3. Select a slide from the lecture and lecture unit.
4. See that nothing gets inserted

### Expected behavior

I'd expect the correct link/image syntax to be inserted into the markdown editor as in the general communication's tab

### Screenshots

![](https://gyazo.com/622a6da67a69e0467446c0788de05318/raw)

### Which version of Artemis are you seeing the problem on?

6.8.0

### What browsers are you seeing the problem on?

Chrome

### Additional context

Here the lecture gets loaded and saved to the field:
https://github.com/ls1intum/Artemis/blob/2e12d79145a02f20a08c9cd4d7eb984823111c2d/src/main/webapp/app/overview/course-lectures/course-lecture-details.component.ts#L75

Here we save it to the discussion section:
https://github.com/ls1intum/Artemis/blob/2e12d79145a02f20a08c9cd4d7eb984823111c2d/src/main/webapp/app/overview/course-lectures/course-lecture-details.component.ts#L87

Here the course gets saved to the cache storage:
https://github.com/ls1intum/Artemis/blob/2e12d79145a02f20a08c9cd4d7eb984823111c2d/src/main/webapp/app/overview/discussion-section/discussion-section.component.ts#L79-L80

And when we attemt to select the slide, this code gets executed:
https://github.com/ls1intum/Artemis/blob/2e12d79145a02f20a08c9cd4d7eb984823111c2d/src/main/webapp/app/shared/markdown-editor/commands/courseArtifactReferenceCommands/lectureAttachmentReferenceCommand.ts#L57

The issue here is that the course is retrieved from the lecture and has hence no lectures on it's own. I'm not sure if this has ever worked or when this bug got introduced. Anyway, the solution here is to find a way to supply all required information to the command through this chain of loading.

### Relevant log output

```shell
ERROR TypeError: Cannot read properties of undefined (reading 'find')
    at ht.execute (lectureAttachmentReferenceCommand.ts:57:63)
    at markdown-editor.component.html:149:88
    at BI (core.mjs:24046:12)
    at o (core.mjs:24083:16)
    at HTMLButtonElement.<anonymous> (platform-browser.mjs:683:112)
    at v.invokeTask (zone.js:371:171)
    at Object.onInvokeTask (core.mjs:14387:25)
    at v.invokeTask (zone.js:371:54)
    at d.runTask (zone.js:173:39)
    at p.invokeTask [as invoke] (zone.js:448:26)
    at C (zone.js:1582:12)
    at D (zone.js:1623:23)
    at HTMLButtonElement.V (zone.js:1643:12)
```

**Comment by PaRangger** [comment] 2024-11-29 21:20
Closing for now, since its not reproducible anymore.

**Closed by PaRangger** 2024-11-29 21:20 UTC
Labels: bug, Component:Lecture, component:Communication
