### ISSUE TITLE
`Quiz exercise`: When I try to reevaluate a large course, it fails

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#5453] opened 2022-07-21 16:26 UTC
### Describe the bug

I reevaluate one quiz exercise in a small course because we made a little mistake in one question. Worked perfect, but with a large course, the process took so long and in the end fails. 

### To Reproduce

1. Go to Course management, 
2. Open a course,
3. Open a solved quiz with more than 180 participants
4. Modify and save the quiz to reevaluate
5. Check that the process takes several minutes and in the end fails. Screenshot

### Expected behavior

Should not fail the process

### Screenshots

<img width="1166" alt="Screenshot 2022-07-21 at 17 55 38" src="https://user-images.githubusercontent.com/88991954/180265389-3d97c49a-d6ed-46cf-a055-4d795205aa83.png">

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment] 2022-07-26 21:04
I don't think this is related to the course size. I would assume there is one student answer that cannot be handled correctly in the re-evaluation due to some kind of edge case. I suggest to look into Sentry to find the cause of this issue

**Comment by krusche** [comment] 2022-10-02 11:00
This issue should be fixed in the latest release.

**Closed by krusche** 2022-10-02 11:00 UTC
Labels: bug
