### ISSUE TITLE
Critical bug: Points are not rounded correctly leading to potentially incorrect grades

### ISSUE THREAD

**Issue by ghagerer** [ls1intum/Artemis#2983] opened 2021-03-08 10:20 UTC
#### Bug description
In our courses, grades are assigned based on absolute points, not based on percentage points. The smallest unit of absolute points for us are mostly 0.5. This means you either have X.0 or X.5 points, with X being an regular integer number. However, the Artemis grading export CSV shows oftentimes different values per exercise and overall, e.g. .6, .8, etc. This leads to a wrong number of points when summed up leading to false grades, potentially making the grades worse and students not passing the course even though they had enough points, which apparently is not desireable.

#### Current workaround
Christian currently provides a workaround by using a raw DB dump from Artemis returning the exact points given by the correcting tutors and summing them up manually. This involves significant extra labor and is prone to bugs, too.

#### To Reproduce
Just look into any CSV export of the overall points from all students of a programming course or exam. I can provide any if necessary.

#### Expected behavior
The assigned points should be shown and summed up correctly in the CSV export.

#### Additional context
This problem should be regarded as critical and urgent, as we are writing repetition exams 26 and 29 March

**Comment by krusche** [comment] 2021-03-08 10:54
Duplicate of #2969 
We are working on a bugfix in #2976 that will be deployed as part of 4.10.6 until Wednesday, March 10.

**Closed by krusche** 2021-03-08 10:54 UTC
Labels: bug
