### ISSUE TITLE
Text exercise assessment

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#1372] opened 2020-05-01 23:07 UTC
### Describe the bug
After assessing a text exercise the assessment is lost (it is shown on the dashboard but not in the submission).
Doing the grading all over again solves the problem.
Another problem is that after dragging the grading template tiles onto the text the overall score isn't updated. Changing one of the points given in a tile updates it for the whole exercise.

#### To Reproduce
1. Asses an text exercise (G01E02 in Eist)
2. Save it
3. Return to exercise dashboard
4. See the correct grading result
5. Go back into the assessment of the submission
6. The grading is lost
7. Regrade and save again
8. Even after leaving and reopening the assessment it is now saved correctly

### Environment

<details><pre>
 - OS: MacOs,  Windows
 - Browser: Safari, Chrome
</pre></details>

**Comment by julian-christl** [comment] 2020-05-01 23:20
Apparently the issue is with the textblocks.
This is a screenshot from an assessment where everything is displayed correctly:
[![Screenshot from Gyazo](https://gyazo.com/bd677adbb20af1f7c28d8ba3adb81fda/raw)](https://gyazo.com/bd677adbb20af1f7c28d8ba3adb81fda)
As you can see the hashes match.

This is a screenshot from an assessment where nothing is displayed even though it was assessed previously:
[![Screenshot from Gyazo](https://gyazo.com/62f5c1ba93fc62cf833c86bb69fd6988/raw)](https://gyazo.com/62f5c1ba93fc62cf833c86bb69fd6988)
As you can see, despite the reference of the feedback this reference doesn't match a textblock at all.

**Comment by HanyaElhashemy** [comment] 2020-05-02 00:21
>Another problem is that after dragging the grading template tiles onto the text the overall score isn't updated. Changing one of the points given in a tile updates it for the whole exercise.
This issue is fixed in #1373

**Comment by krusche** [comment] 2020-05-03 11:14
The main issue should be fixed by a hot fix of @jpbernius tonight. Can you check if it works again?

**Comment by JohannesStoehr** [comment] 2020-05-03 11:43
The main issue is fixed!

**Closed** 2020-05-05 16:31 UTC
Labels: bug
