### ISSUE TITLE
Fast Scrolling speeds not supported in Online Editor

### ISSUE THREAD

**Issue by janik6882** [ls1intum/Artemis#4777] opened 2022-03-04 18:05 UTC
### Describe the bug

Scrolling in Web Editor not working with at faster speeds for hardware supporting those speeds.

### To Reproduce

1. Go to 'https://artemis.praktomat.cs.kit.edu/courses/[Number]/[Course-Name]/code-editor/[Number, i can't identify]'
2. Click on the Code which shall be edited
3. Scroll down/up in Editor using a mouse supporting fast Scrolling (Tested using Logitech MX Master)
4. Scrolling Stops and continues in main Page (outside editor)

### Expected behavior

By user (which I am) scrolling would be expected to continue, not abruptly stop. Bug does not occur when scrolling through Web Editor File Browser

### What browsers are you seeing the problem on?

Firefox

### Additional context

Tested on Logitech MX Master, Firefox 97.0.1 (64-Bit), Windows 10, poses no Problem on standard html Input tag on other websites.

**Comment by Hialus** [comment] 2022-03-04 19:00
I can mostly confirm this bug.
Tested it in Windows 10 with Firefox and Chrome using an MX Master 3. With Firefox I can reliably reproduce the bug. With Chrome it does not happen.
I also tested in on macOS with Firefox and Safari using the build-in trackpad. In both cases, the bug appears even when scrolling only slowly.
I can also confirm that this is unique to the Ace editor and I could not reproduce it anywhere else on Artemis.

**Comment by krusche** [comment] 2022-03-05 14:08
I don't think we can fix that on the Artemis side. Can you report it to the ace editor developers?

**Comment by janik6882** [comment] 2022-03-05 14:38
> I don't think we can fix that on the Artemis side. Can you report it to the ace editor developers?

Is this the right GitHub Repo?
https://github.com/ajaxorg/ace

If this is the right Repo, that should be possible. If necessary I would quote this issue for version info or what may be needed if this works out for you.

**Comment by b-fein** [comment] 2022-05-19 13:59
Seems to have been fixed with ace 1.5.0 https://github.com/ajaxorg/ace/issues/4647 that is already used by Artemis. https://github.com/ls1intum/Artemis/blob/760e9e73ccdd60023bb9c83be6a58a1fead95d64/package.json#L37

**Closed by b-fein** 2022-05-19 13:59 UTC
Labels: bug
