### ISSUE TITLE
Show Sample Solution

### ISSUE THREAD

**Issue by pstoeckle** [ls1intum/Artemis#4006] opened 2021-09-15 11:31 UTC
### Is your feature request related to a problem?

In some exams, one wants to present a sample solution to the students. As far as I know, this is currently not possible in Artemis.

### Describe the solution you'd like

A check box "Show sample solution during the review" for the exam and for the exercise groups. If the exam's check box is checked, the students see all sample solutions for all exercises. If the exam's checkbox is not checked, only the sample solutions for exercises are presented whose exercise groups' checkboxes are checked. 
At least for text exercises this would be very useful.

**Comment by MaisiKoleni** [comment] 2021-09-23 23:57
Possible duplicate of #16, at least directly related. At the time of me writing this, @akesfeden started working on that issue. (@akesfeden I tagged you, so you are aware of this issue. I think you know better than me what the plan is and how to respond)

**Comment by pstoeckle** [comment] 2021-09-27 15:38
> Possible duplicate of #16, at least directly related. At the time of me writing this, @akesfeden started working on that issue. (@akesfeden I tagged you, so you are aware of this issue. I think you know better than me what the plan is and how to respond)

Sorry, I have searched for related things in the recent issues, but not back until 2017 😅

**Comment by akesfeden** [comment] 2021-09-28 00:47
Currently I am working on a solution involving a new `solutionPublicationDate` Exercise attribute described here https://github.com/ls1intum/Artemis/issues/16#issuecomment-729582042 I am working on Modeling Exercises but I think the plan is to extend this feature to other exercises and maybe exams as well.

I think after conditional authorization of students to sample solutions is established, making it more granular (i.e. dis/allow access for each exercise group) would also be possible.

**Comment by krusche** [comment] 2022-02-25 17:51
I would actually define this exam wide and not for single exercises / exercise groups in exams.
There is already a result publication date, so we basically only need to add a boolean flag whether the example solutions should be published or not. Then on the exam summary, there could e.g. be a link to show them in separate pages

**Closed** 2023-02-13 21:54 UTC
Labels: feature
