### ISSUE TITLE
`Plagiarism checks`: New tutors and editors cannot run plagiarism checks 

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#5470] opened 2022-07-25 12:19 UTC
### Describe the bug

New tutors and editors cannot run plagiarism checks. 
Specific case: If a tutor had Tutor and/or Editor role(s) in a course before the last Artemis update, he/she can run the plagiarism check. If I (instructor) assign him/her as Tutor and/or editor in another course, now he/she cannot run a plagiarism check. 

### To Reproduce

Instructor
1. Go to Course Manager
2. Click on a course
3. Scroll down to participants and add at least one user as editor and/or tutor
Tutor
4. Go to Course Manager
5. Click on a course
6. Run a plagiarism check
8. Verify you are not allowed to do that

### Expected behavior

The editor role should be able to run plagiarism checks. 

### What browsers are you seeing the problem on?

Chrome

**Comment by fh314** [comment] 2022-07-26 09:43
Duplicate of #5467

**Closed** 2022-08-01 05:32 UTC
Labels: bug, plagiarism detection
