### ISSUE TITLE
Navigating to Messages or Communication within "Course Management" results in being logged out of course management.

### ISSUE THREAD

**Issue by egekurt123** [ls1intum/Artemis#7479] opened 2023-10-31 12:11 UTC
### Describe the bug

When using a tutor, admin, or instructor user account and attempting to access the "Messages" or "Communication" feature within the Course Management section. Instead of accessing the messaging functionality within the Course Management interface, the user is immediately logged out of the Course Management section.

### To Reproduce

1- Access the Course Management section using a tutor, admin, or instructor user account.
2- Select the "Messages" or "Communication" option from the menu.
3- This action automatically navigates you out of the Course Management interface, requiring you to return to the Course Management section in order to make further edits or modifications.

### Expected behavior

 Accessing the messaging functionality within the Course Management interface

### Which version of Artemis are you seeing the problem on?

6.6.3

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

**Comment by PaRangger** [comment] 2024-11-29 21:22
Closing this for now due to not being reproducable anymore.

**Closed by PaRangger** 2024-11-29 21:22 UTC
Labels: bug, component:Communication
