### ISSUE TITLE
Cannot edit interface names on Safari

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/Artemis#484] opened 2019-05-23 08:39 UTC
### Describe the bug
https://eist2019.slack.com/archives/CGLDT1EG3/p1558600590094600

The interface is moving upwards instead of showing the edit popover on double-click.

**Comment by jpbernius** [comment] 2019-08-20 09:48
I cannot reproduce this issue any more, so I assume this is fixed by now. Please reopen this issue if it is still relevant!

**Closed by jpbernius** 2019-08-20 09:48 UTC
Labels: bug
