### ISSUE TITLE
Static analysis issue preview is failing for C exercises

### ISSUE THREAD

**Issue by alexanderstephan** [ls1intum/Artemis#4557] opened 2021-12-26 14:38 UTC
### Describe the bug

For C static analysis the preview beneath `(See more)` in the programming exercise results fails to be displayed properly. A unparsed JSON like string is shown. Presumably the raw result that is sent to Artemis from the Bamboo SCA Plugin.

### To Reproduce

Create a C programming exercise and produce a static analysis issue that produces a static analysis report that is long enough to need a preview.

### Expected behavior

Properly parsed string without a JSON formatting visible after `(See more)`. See screenshots below for reference.

### Screenshots

Unparsed JSON string in preview:
![image](https://user-images.githubusercontent.com/30267166/147411223-6a7e4f5a-6dcb-4f13-8a14-9d9f80df41f5.png)

How it should like (not collapsed, so this should be condensed for the preview):
![image](https://user-images.githubusercontent.com/30267166/147411244-2b750502-6736-44e3-92a8-91e51c73099b.png)

### What browsers are you seeing the problem on?

Firefox

**Comment by Strohgelaender** [comment] 2021-12-26 15:06
This is a duplicate of #4412 and will be fixed by #4552.

**Closed by Strohgelaender** 2021-12-26 15:06 UTC
Labels: bug
