### ISSUE TITLE
🚀 Submission status

### ISSUE THREAD

**Issue by antonisikorski** [ls1intum/Artemis#427] opened 2019-05-09 09:37 UTC
### Is your feature request related to a problem?
It is easy to verlook an excericse not submitted yet (before the deadline).

### Describe the solution you'd like
A flag or a color bar indicating if an excercise is not solved yet and the deadline has not yet passed. 
![artemis](https://user-images.githubusercontent.com/50444366/57443629-c6cf4a00-724e-11e9-96f1-89e67cab6939.png)

### Describe alternatives you've considered
A view of excercies without a solution before the deadline

**Comment by vincko** [comment] 2019-05-09 12:22
+1

Here is an alternative suggestion to solve the problem: 
Add a 'No submission' status for exercises that have been started, but not yet submitted.
(Instead of having 'No result' for both submitted and not yet submitted exercises)

**Comment by vincko** [comment] 2019-05-09 12:27
This is a possible duplicate of #403

**Closed** 2019-11-10 23:36 UTC
Labels: feature
