### ISSUE TITLE
Build Failed after correct submission

### ISSUE THREAD

**Issue by SherbertLemon77** [ls1intum/ArTEMiS#478] opened 2019-05-22 09:50 UTC
### Describe the bug
About a day after I submitted my code homework and got 100%, the evaluation changed to build failed. 

#### To Reproduce
Submit correct code homework. 
About a day later scroll down to check results, it says 0% and build failed. 

#### Expected behavior
I expected to still see 100%. 

#### Screenshots
This is the output I got when clicking on my error: 
![Screenshot 2019-05-14 at 11 09 59](https://user-images.githubusercontent.com/50132725/58165221-a1e3c980-7c87-11e9-8670-f0c1c982d99d.png)

### Environment
 - OS: ios
 - Browser: chrome
 - Version 74.0.3729.157 (Official Build) (64-bit)

**Comment by krusche** [comment] 2019-06-16 15:14
I am not sure what has happened here. This is definitely not the intended behavior. Could you send me a private message on Slack with your TUM Identifier and the exercise name. Then I will have a look why this happened, how we can prevent it in the future and also make sure that you see the correct result.

Closing this issue here as it is most probably course related.

**Closed by krusche** 2019-06-16 15:14 UTC
Labels: bug
