### ISSUE TITLE
Bug which prevents Lectures from being edited (for instructors).

### ISSUE THREAD

**Issue by podolskyDavid** [ls1intum/Artemis#3089] opened 2021-03-28 16:26 UTC
### Describe the bug

A problem while saving changes to Lecture in Edit mode. Button "Save" doesn't respond.

#### To Reproduce

Prerequisites: 
1. Having an access to Course Management function;
2. Having a pre-existing Lecture to edit.

Steps to reproduce:
1. Go to 'https://artemis.ase.in.tum.de/courses';
2. Click 'Course Management' tab;
3. Click "Lectures" button in any of the courses;
4. Click "Edit" button to the right of any Lecture in the list;
5. Make any changes to the Lecture;
6. Try clicking "Save" button.

#### Expected behavior

After clicking "Save" button should post/save changes and forward to the list of Lectures corresponding to the current course in "Course Management" tab.

#### Screenshots

Presumable edits:
<img width="1280" alt="Screenshot 2021-03-28 at 18 07 22" src="https://user-images.githubusercontent.com/63861055/112758884-d0076280-8ff0-11eb-8da0-749f5dc28513.png">

Actual state:
<img width="1280" alt="Screenshot 2021-03-28 at 18 08 07" src="https://user-images.githubusercontent.com/63861055/112758903-e7465000-8ff0-11eb-80bf-09277a14e1e4.png">

#### Additional context

Tested this behaviour with and without attachments (such as files or exercises). The only way around is to delete Lecture.

### Environment

<details><pre>
 - OS: macOS Big Sur v.11.2.3
 - Browser: chrome
 - Version: latest at the time of writing
</pre></details>

**Comment by krusche** [comment] 2021-03-29 07:45
We tried it out and we cannot reproduce the described issue. We have tried out multiple environments (Test Server + Production Server) and multiple browsers (Chrome, Safari, Firefox).

The save button is only deactivated when the title is empty (indicated with a red flag) and during the save operation (which typically takes less than 1s), afterwards the user is immediately navigated to the previous page.

Can you try it again? Please try to provide more details (e.g. a screencast) when the issue happens again. Feel free to reopen the issue then.

**Comment by krusche** [comment] 2021-03-29 07:47
We just found something. It could be related to the use of lecture units

**Comment by krusche** [comment] 2021-03-29 07:47
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/744067/112803615-cd018600-9073-11eb-9239-623b7c75140a.png">

**Comment by podolskyDavid** [comment] 2021-03-29 08:45
Just tried to reproduce it with Lecture without Lecture Units and could successfully save the edits. As you mention, the problem might be with Lecture Units. I was able to reproduce the issue with the Lecture, which has Units attached to it.

**Comment by podolskyDavid** [comment] 2021-03-29 10:17
If you need any further information, I will gladly provide it.

**Comment by krusche** [comment] 2021-05-20 20:32
I assume the issue has been fixed by now, but was not yet closed

**Closed by krusche** 2021-05-20 20:32 UTC
Labels: bug
