### ISSUE TITLE
Cannot update the Grading Instructions

### ISSUE THREAD

**Issue by pstoeckle** [ls1intum/Artemis#3448] opened 2021-05-18 11:47 UTC
### Describe the bug

I'm grading student submissions using the *Structured Grading Instructions* (awesome feature!).
While grading the submissions, I wanted to add a grading instruction, but I always received a `Http failure response for https://artemis.ase.in.tum.de/api/text-exercises: 500 OK` error.

#### To Reproduce

1. Create an exercise
2. Create *Structured Grading Instructions*
3. Save
4. Maybe add a student submission?
5. Open the exercise again.
4. Add a *Structured Grading Instructions*
5. Error!

Even if you delete all the grading instructions, it will fail.

#### Expected behavior

The structured grading scheme should be updated.

#### Screenshots

![ce65e](https://user-images.githubusercontent.com/5854768/118645284-04242600-b7df-11eb-91bd-824c0b56665c.png)

#### Output in Web Console

JSON payload sent

```json
{
    "type": "text",
    "id": 4057,
    "title": "Security, Usability, Psychology",
    "releaseDate": "2021-04-20T22:00:00.000Z",
    "dueDate": "2021-04-30T21:59:00.000Z",
    "maxPoints": 1,
    "bonusPoints": 0,
    "assessmentType": "MANUAL",
    "includedInOverallScore": "NOT_INCLUDED",
    "problemStatement": "bla",
    "gradingInstructions": "You",
    "mode": "INDIVIDUAL",
    "presentationScoreEnabled": false,
    "secondCorrectionEnabled": false,
    "course": {
        "id": 130,
        "title": "Security Engineering (IN2178) SS21",
        "description": "Bla",
        "shortName": "seceng21",
        "studentGroupName": "artemis-seceng21-students",
        "teachingAssistantGroupName": "artemis-seceng21-tutors",
        "editorGroupName": "artemis-seceng21-editors",
        "instructorGroupName": "artemis-seceng21-instructors",
        "startDate": "2021-04-12T00:00:00+02:00",
        "endDate": "2021-10-15T23:00:00+02:00",
        "semester": "SS21",
        "testCourse": false,
        "onlineCourse": false,
        "maxComplaints": 3,
        "maxTeamComplaints": 3,
        "maxComplaintTimeDays": 7,
        "studentQuestionsEnabled": true,
        "maxRequestMoreFeedbackTimeDays": 7,
        "color": "#94a11c",
        "courseIcon": "/api/files/course/icons/130/CourseIcon_2021-04-08T15-36-12-172_f4752830.png",
        "registrationEnabled": true,
        "presentationScore": 0,
        "requestMoreFeedbackEnabled": true,
        "complaintsEnabled": true
    },
    "gradingCriteria": [],
    "automaticAssessmentEnabled": false,
    "visibleToStudents": true,
    "studentAssignedTeamIdComputed": false,
    "released": true,
    "teamMode": false,
    "ended": true,
    "studentParticipations": []
}
```

JSON response

```json
{
    "type": "https://www.jhipster.tech/problem/problem-with-message",
    "title": "Internal Server Error",
    "status": 500,
    "detail": "could not execute batch; SQL [delete from grading_instruction where id=?]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch",
    "path": "/api/text-exercises",
    "message": "error.http.500"
}
```

**Comment by krusche** [comment] 2021-05-20 20:27
This is a duplicate of #3038 that just has been fixed by @imstreetspirit in #3294.
The fix will be deployed with the next release 4.12.3 which should be available on Saturday.

**Closed by krusche** 2021-05-20 20:27 UTC
Labels: bug
