### ISSUE TITLE
Default Arrow direction in Apollon Communication Diagrams

### ISSUE THREAD

**Issue by DemonInTheCloset** [ls1intum/Artemis#1444] opened 2020-05-10 22:16 UTC
### Is your feature request related to a problem?
It's frustrating that when using Apollon to draw Communication Diagrams, the message arrows go opposite to the expected direction, and the messages stack opposite to the expected way.

### Describe the solution you'd like
I would like that when connecting A to B, the message arrow goes by default from A to B instead of from B to A.
And that the messages should stack from top to bottom instead of from bottom to top.

### Additional context
Screenshots:
Connect A to B and add these messages:
![Take 1](https://user-images.githubusercontent.com/41545008/81511834-10cb8f80-92ea-11ea-8d83-a94abc774741.png)
When flipping the arrow direction from 2.1 and 2.2 this happens
![Take 2](https://user-images.githubusercontent.com/41545008/81511831-09a48180-92ea-11ea-94cd-e352305adf6c.png)

**Comment by TobiasPr** [comment] 2020-05-21 08:29
@DemonInTheCloset I solved the issue in Apollon. Will be included in the release 2.0.15

Here is a screenshot of the result, this should solve your issue:
![image](https://user-images.githubusercontent.com/22955066/82539503-d5cd2580-9b4d-11ea-8259-9ccb8982ff58.png)

**Comment by TobiasPr** [comment] 2020-05-21 09:11
I realized, that there are certain cases, where the text is displayed differently. SO the issue is not solved
![image](https://user-images.githubusercontent.com/22955066/82543455-d9fc4180-9b53-11ea-839d-f9d2cacf4e75.png)

**Comment by TobiasPr** [comment] 2020-05-31 09:01
Solved in Apollon 2.0.18

**Closed by TobiasPr** 2020-05-31 09:01 UTC
Labels: component:Modeling, feature
