### ISSUE TITLE
Remember last cloning method 

### ISSUE THREAD

**Issue by TheMC47** [ls1intum/Artemis#2363] opened 2020-11-07 08:15 UTC
### Is your feature request related to a problem?
Right now, when I choose `ssh` for example to clone a repository, I can do it. When I try to clone another repository, I need to manually select `ssh` again.

### Describe the solution you'd like
It would be nice for artemis to remember the last method of cloning.

**Comment by krusche** [comment] 2020-11-08 11:58
Duplicate of #2317

**Closed by krusche** 2020-11-08 11:58 UTC
Labels: feature
