### ISSUE TITLE
ssh-key does not work when cloning a git repository on Bitbucket

### ISSUE THREAD

**Issue by DomiAb** [ls1intum/Artemis#4143] opened 2021-10-15 14:09 UTC
### Describe the bug

I entered a ssh-key in bitbucket. When I try git clone ssh://git@bitbucket.ase.in.tum.de:7999/........git a get the warning:
"git@bitbucket.ase.in.tum.de: Permission denied (publickey).
fatal: Konnte nicht vom Remote-Repository lesen."
The rights of the ssh-file on my device are set correctly. I heard from other people, that they have the same problem.

### To Reproduce

1. Enter a new ssh-key on bitbucket (produced with ssh-keygen -t ed25519 -b 4096)
2. Copy the url from the artemis excercise
3. Try git clone $url$

### Expected behavior

I would expect a clean git clone without a mistake. The normal git clone works, just the cloning with ssh fails.

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

linux ubuntu

**Comment by jakobkukla** [comment] 2021-11-03 19:01
@krusche Please reconsider closing this issue.

**Comment by krusche** [comment] 2021-11-03 20:21
@jakobkukla can you let us know which environment you are using?

**Comment by krusche** [comment] 2021-11-03 20:21
@Mtze we should further investigate why some users (apparently on Linux) have issues with cloning over SSH

**Comment by jakobkukla** [comment] 2021-11-03 21:22
@krusche I'm having this issue on 3 different Arch Linux installations using recent versions of git and openssh (2.33.1 and 8.8p1 respectively). All of them using different ssh-keys which 1) worked before with Artemis and BitBucket and 2) work on GitHub and other services.

I believe the issue first appeared sometime this summer. I first noticed it preparing for the EIST Retake in early October.

**Comment by jakobkukla** [comment] 2021-11-03 21:27
I just spun up my old Windows 10 installation, created a new key there and added it to the BitBucket instance. Same result: Cloning from GitHub works flawlessly. Artemis and BitBucket give a permission denied error.

**Comment by Mtze** [comment] 2021-11-03 21:39
This problem occurred several times in last few weeks. Up until now we only saw this on arch-based clients. The openSSH version on arch apparently rejects all possible signature algorithms: 

You can verify that this is the case by running 
```
GIT_SSH_COMMAND="ssh -vvv" git clone <your repo url>
```
and search for the following output:
```
debug1: send_pubkey_test: no mutual signature algorithm
```

I will have a look if we can do something about that. 

If you need a quick solution to this, generate a new ed25519 key and register the key in bitbucket. This key type should be unaffected. 

Best, 
Matthias

**Comment by jakobkukla** [comment] 2021-11-03 21:39
Ok this was my fault after all. Apparently BitBucket stopped accepting RSA keys while GitHub still does. Creating an ed25519 key solved the issue. Sorry for the inconvenience caused.

**Comment by jakobkukla** [comment] 2021-11-03 21:57
I checked under Windows again. Using OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2:

debug1: Offering public key: /c/Users/Jakob Kukla/.ssh/id_rsa RSA SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
debug1: send_pubkey_test: no mutual signature algorithm

**Comment by jakobkukla** [comment] 2021-11-03 22:22
Apparently this is not a bug: https://confluence.atlassian.com/bitbucketserverkb/ssh-rsa-key-rejected-with-message-no-mutual-signature-algorithm-1026057701.html

**Comment by krusche** [comment] 2021-11-04 06:46
@Mtze thanks for clarifying this. I guess if RSA is insecure and will be deprecated, we should not support any more in Bitbucket. The only improvement I can imagine is a better error message when the clone operation is denied, but this is probably not in our hands

**Closed by krusche** 2021-11-04 06:46 UTC
Labels: bug, bamboo/bitbucket
