### ISSUE TITLE
Mass Import for Exercises

### ISSUE THREAD

**Issue by severin-kacianka** [ls1intum/Artemis#3818] opened 2021-07-21 12:25 UTC
### Is your feature request related to a problem?

For the PGdP exercise preparation, I'd like to share the exercises of the two old courses with some new colleges, without adding them to the old courses (so they also don't have access to any student data). Basically I'd like to bulk-import a set of ~150 existing exercises from two existing courses into a single new course. 
The new course would basically be the 'exercise repository' my colleagues can use to derive new exercises from.  

### Describe the solution you'd like

The best solution would be a button in the GUI that allows me to select multiple exercises to import. 

Another option would be to just do it in a 'hacky' way on the server-side. This would solve my immediate problem and already be very helpful. 

The third solution is to add all colleagues to the two old courses... but this grant access to student data to a lot of people. 

A final solution might be to offer an 'export' feature for all exercises that could output all exercises as a zip file. 

### Describe alternatives you've considered

An option I have right now is to manually import each exercise one-by-by. However... we are talking about ~150 exercises.. so this would be a lot of work.

**Comment by MaisiKoleni** [comment] 2021-08-08 17:31
You can already do it the hacky way by using the API programmatically. There is an endpoint for exercise import. I think this would be a larger feature to properly implement, because some updates and setting changes are typically done on import (what is shown on the import page).

**Comment by krusche** [comment] 2021-10-13 10:13
duplicate of #3765

**Closed by krusche** 2021-10-13 10:13 UTC
Labels: feature
