### ISSUE TITLE
'Programming exercises': Clone button does not show the link

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#8032] opened 2024-02-14 10:31 UTC
### Describe the bug

Clone button does not show the link

### To Reproduce

1. Go to any programming exercise as instructor. 
2. Verify that is not possible to see the button to clone the exercise template solution or tests. See the screenshot bellow 

### Expected behavior

Should show the link and the button for copy the link. 

### Screenshots

<img width="914" alt="image" src="https://github.com/ls1intum/Artemis/assets/88991954/ea06c5c0-549f-4d3b-857e-987cb9018c6d">

### Which version of Artemis are you seeing the problem on?

6.8.0

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by b-fein** [comment] 2024-02-14 13:35
Duplicate of #8024.

**Closed by b-fein** 2024-02-14 13:35 UTC
Labels: bug, component:Programming, priority:high
