### ISSUE TITLE
Assessment board wrongly formats Student answer 

### ISSUE THREAD

**Issue by 1-alex98** [ls1intum/Artemis#3015] opened 2021-03-14 12:35 UTC
### Describe the bug
What the student handed in(only part of it):
![Screenshot from 2021-03-14 13-14-55](https://user-images.githubusercontent.com/19996713/111068045-54bd9100-84c7-11eb-9284-064d8b067b23.png)
It is shown this way in the /participation view.
But in the /assesment view it looks like:
![Screenshot from 2021-03-14 13-13-32](https://user-images.githubusercontent.com/19996713/111068080-85052f80-84c7-11eb-986c-67db07f2d99d.png)
Instead of formatting it correctly, the view leaves out the newlines and instead repeats the last character of the lines before(Every time). Notice how there is an extra 8. 297488 instead of 29748 for example.

Student lost points for this before he complained. It is also only one student for everybody else it seemed to work.

The text the student handed in copied from the network tab in the developer section:
```
"text":"\nAusgabe nach jedem Durchlauf der while-Schleife:\nnicht ausgegeben : 2 9 4 7 8\nAusgabe:\n2 4 7 8 9\n2 4 7 8\n2 4 7\n2 4 \n2 \n\nDas Array ist nach dem ersten Schleifendurchlauf schon sortiert. Dennoch wiederholt sich die Ausgabe so oft wie die Länge des Arrays (-1 jeder Schleifendurchlauf). Jeder Schleifendurchlauf wird ein Arrayelement weniger ausgegeben.\n\n\nAufgabe 2:\nEs handelt sich um das Sortierverfahren Bubble-Sort."
```

#### To Reproduce

Put a newline at the start of a text exercise messes up the answer. But not only this also other newlines seem cause issues.

Also copying the text above in the database in the submission table should do to reproduce.

Removing the newline at the start makes many issues dissapear but causes new ones :D Now we have double letters at other locations:
![Screenshot from 2021-03-14 13-32-32](https://user-images.githubusercontent.com/19996713/111068602-c1398f80-84c9-11eb-9f57-9991c671cd0f.png)

#### Severity
Pretty painful bug, makes students loose points especially if numbers are involved and the website adds numbers that were not there before. And not all students are gonna complain.

**Comment by 1-alex98** [comment] 2021-03-14 12:42
We are still at version 4.10.0 ... We will update and see if that maybe helps already

**Comment by 1-alex98** [comment] 2021-03-14 12:45
I read about formatting issue in release notes just do not know what exactly they were.

**Comment by 1-alex98** [comment] 2021-03-14 12:46
By guess would be \n\n or \n at the start cause this

**Comment by Strohgelaender** [comment] 2021-03-14 16:55
Did you try pressing the alt-key in the assessment view? Also with version 4.10.1 #2895 was fixed which seems related (at least for the duplicated chars you mentioned at the end).

**Comment by 1-alex98** [comment] 2021-03-15 15:36
I think I am gonna update before the next exam. What does pressing alt key do?

**Comment by 1-alex98** [comment] 2021-03-15 15:44
Pressing alt removes double letters

**Comment by 1-alex98** [comment] 2021-03-15 15:46
I finally understood what alt does :D Nice. Just did not get that I had to mark the text then...

**Comment by krusche** [comment] 2021-03-15 20:30
@jpbernius could you please check if the mentioned issue still occurs in the newest Artemis version? If yes, we should fix it.
If not, please close the issue

**Comment by jpbernius** [comment] 2021-03-15 21:35
I tested this with `4.11.0` and cannot reproduce the issue for this Text:
```
nicht ausgegeben : 2 9 4 7 8 
Ausgabe:
2 4 7 8 9 
2 4 7 8 
2 4 7 
2 4 
2
Das Array ist nach dem ersten Schleifendurchlauf schon sortiert.
```
Every line is a Textblock that can be reviewed individually.

We fixed an issue that was caused by leading whitespace in #2891.

**Closed by jpbernius** 2021-03-15 21:35 UTC
Labels: bug

**Comment by 1-alex98** [comment] 2021-03-17 16:16
I am still waiting for the grade to be copied from the system. But I am gonna update Artemis after that then ;) Thx a lot
