### ISSUE TITLE
Behaviour after overriding an assessment when having a complaint is not consistent

### ISSUE THREAD

**Issue by fde312** [ls1intum/Artemis#2129] opened 2020-09-27 21:16 UTC
### Describe the bug

For text exercises, when you (as instructor) override an assessment while having a complaint, it does keep the complaint elements in the tutor assessment view.
This is not the case for modeling and file upload and programming, there the elements are not visible anymore but not deleted in the database. In the student view the complaint elements are still there.

ModelingAssessmentService.java: 85 -> result.setHasComplaint(false);
FileUploadAssessmentService.java: 74 -> result.setHasComplaint(false);
ProgrammingAssessmentService.java:37 -> result.setHasComplaint(false);

A fix would be to fetch the complaint and set the result.hasComplaint value according if the fetch returned a element or not. :) 

#### To Reproduce

1. Create exercise, participate, assess 
2. Complain about assessment
3. Accept/reject complaint or leave it without answering
4. Override accepted complaint assessment as instructor
5. Complaint DOM elements are not there anymore

#### Expected behavior

We assume that the complaint elements should still be visible also after the override from instructor. Maybe @krusche can clarify :)

**Comment by MaisiKoleni** [comment] 2021-01-27 18:52
You can also answer a complaint, that does not make any difference.

**Comment by krusche** [comment] 2021-02-26 13:10
might be a duplicate of https://github.com/ls1intum/Artemis/issues/2026

**Comment by krusche** [comment] 2021-02-26 13:11
overriding a result should not lead to issues with the complaints, so we should fix this bug

**Comment by krusche** [comment] 2021-02-26 13:15
there might habe been a bugfix in #2619 
however, @MaisiKoleni reported that the issue is still possible after the corresponding version has been released.

The code has moved into AssessmentService.java:341 anyway and at least seems to be consistent for all exercise types

**Closed** 2021-03-06 20:59 UTC
Labels: bug, component:FileUpload, component:Modeling, component:Programming, server
