### ISSUE TITLE
`Programming exercises`: sticky scrolling cannot be disabled in the online editor

### ISSUE THREAD

**Issue by BaumiCoder** [ls1intum/Artemis#8514] opened 2024-04-30 15:23 UTC
### Describe the bug

In the new online editor for student submission (https://github.com/ls1intum/Artemis/pull/8130), for instructors editing repos (https://github.com/ls1intum/Artemis/pull/8389) and tutors to assess submissions (https://github.com/ls1intum/Artemis/pull/8437) there is a "sticky scrolling". This means that the headers of upper structure elements (e.g., methods, classes) stick on top of the editor as long as you are in this element.

This disturbs some users. One reason is that the other lines sometimes "jump" a bit up and down while the sticky lines appears / disappears. Another problem is on smaller screens, where the space consume is a problem.

---
Monaco seems to have options for this: [IEditorStickyScrollOptions](https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorStickyScrollOptions.html)
I do not know if there is also an option to gave users access to these settings.

### To Reproduce

1. Open the online editor somewhere in Artemis
2. Open a file with a longer class to be able to scroll down
3. Scroll down until the class header get out of the view
4. "Sticky scrolling" take action and cannot be removed

### Expected behavior

I am able to remove the sticky scrolling. This decision should be saved (e.g. for the user or in the session).

In VSCodium for example I can use the Popup-Menu on the "sticky scrolling" to remove it or a command from the "Command Pallet" (F1)

### Screenshots

![sticky scrolling](https://github.com/ls1intum/Artemis/assets/73783062/10a05c24-ace8-47c0-be4d-70bb19b6fb6a)

### Which version of Artemis are you seeing the problem on?

7.0.2

### What browsers are you seeing the problem on?

Firefox

**Comment by pzdr7** [comment] 2024-04-30 16:32
Interestingly, this toggle seems to be (partially) implemented in the Monaco editor. Unfortunately, it also seems broken at the moment, as can be reproduced in the [Monaco playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.48.0#XQAAAAJwAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscwzedd-_1uhs0-3YGTBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKiqzCsumz7pId1IzUGaNhChbJ9YJCAG6kwDvSsxR-e2thzsiWpxXcaN4KiGrKhjt2qlP0j55VwQsOuP27foRkWbyCDTNFCrVkloSD0wnsxSrMQevE9V3nWu5tNCwBgqhgMocOWYYFqWKaE4N9ml0jWjnFvDO-48F_feVaLemT_RSWDqa2LEvQmrxWpysZ0gJFtHAktAY5z5B7wcw9yXgAZ6F-8FeRP-afzm1CioJEI48WR_O9qjKJXjefP__RETwg).


https://github.com/ls1intum/Artemis/assets/38403547/5fdf8816-1f37-4b09-a1f0-9535462aa3fc

**Comment by pzdr7** [comment] 2024-04-30 17:37
I have opened the issue https://github.com/microsoft/monaco-editor/issues/4488 in the Monaco editor repository. I suggest we wait until that issue is resolved before addressing this one.

**Comment by chrisknedl** [comment] 2024-11-04 08:59
Since sticky scrolling is now disabled by default, the main reason for this issue i resolved, so I think we can close this.

**Closed by chrisknedl** 2024-11-04 08:59 UTC
Labels: bug, component:Programming
