### ISSUE TITLE
Bug beim öffnen von More Feedback Requests.

### ISSUE THREAD

**Issue by nicolaihornung** [ls1intum/Artemis#1079] opened 2019-11-18 14:00 UTC
### Describe the bug
Instantly closes the opened tab upon pressing the Show Request Button in the List of More Feedback Requests Dialogue. JS Error Message is attached below.

#### To Reproduce
Course Administration > Tutor Course Dashboard > Feedback Requests about your Assessments > Show the Request

The corresponding Exercise is W02H02 of PGdP. As this is a Programming Exercise and Feedback Requests on File Upload Exercises have worked so far maybe thats the problem. 

#### Expected behavior
Well it should open the Feedbackpage...

#### Screenshots

![grafik](https://user-images.githubusercontent.com/46528800/69133311-fab8e100-0ab5-11ea-8ebb-4ca6e3e4a639.png)

URL: https://artemis.ase.in.tum.de/#/more-feedback-requests?courseId=37&tutorId=8234

### Environment

<details><pre>
 - OS: Windows 10
 - Browser: Chrome, Firefox, Edge 
 - Version Chrome: 78.0.3904.97 Firefox: 70.0.1, Edge: 44.18362.449.0
</pre></details>

#### Output in Web Console

<details><pre>
breadcrumbs.js:64 ERROR Error: The requested path contains undefined segment at index 0
    at router.js:7822
    at on.navigate (router.js:7449)
    at BW.openAssessmentEditor (list-of-complaints.component.ts:102)
    at Object.handleEvent (main.6e5e2825500ebb4455bc.bundle.js:2)
    at Object.handleEvent (core.js:43993)
    at Object.handleEvent (core.js:44774)
    at wp (core.js:29804)
    at core.js:42925
    at HTMLButtonElement.<anonymous> (platform-browser.js:2668)
    at HTMLButtonElement.l (helpers.js:74)
    at t.invokeTask (zone.js:431)
    at Object.onInvokeTask (core.js:39680)
    at t.invokeTask (zone.js:430)
    at e.runTask (zone.js:198)
    at e.invokeTask [as invoke] (zone.js:513)
    at m (zone.js:1671)
    at HTMLButtonElement.b (zone.js:1697)
(anonymous) @ breadcrumbs.js:64
Ar @ core.js:6014
handleError @ core.js:6066
handleError @ sentry.error-handler.ts:49
wp @ core.js:29808
(anonymous) @ core.js:42925
(anonymous) @ platform-browser.js:2668
l @ helpers.js:74
t.invokeTask @ zone.js:431
onInvokeTask @ core.js:39680
t.invokeTask @ zone.js:430
e.runTask @ zone.js:198
e.invokeTask @ zone.js:513
m @ zone.js:1671
b @ zone.js:1697
</pre></details>

**Comment by krusche** [comment] 2019-11-18 14:24
Please add a screenshot and and the url where this error occurs.
Also more details would be helpful, otherwise we cannot reproduce and fix this error!

**Comment by 13XxM1CHA3lxX37** [comment] 2019-11-19 09:15
#1037

**Comment by maxr96** [comment] 2019-11-19 09:57
Thank you for reporting the bug @nicolaihornung. I am working on it in #1030. This will also fix #1037 as mentioned by @13XxM1CHA3lxX37

**Comment by maxr96** [comment] 2019-12-12 21:09
Fixed in #1030

**Closed by maxr96** 2019-12-12 21:09 UTC
Labels: bug
