### ISSUE TITLE
Text in Text Editor with active dark mode is unreadable

### ISSUE THREAD

**Issue by LadnerJonas** [ls1intum/Artemis#5137] opened 2022-05-22 12:32 UTC
### Describe the bug

The text is black with a black background. This Bug was added with 5.8.2.

### To Reproduce

1. Go to any Text Exercise
2. Write a few letters
3. See a black text on a black background

### Expected behavior

White text on a black background

### Screenshots

![image](https://user-images.githubusercontent.com/92096842/169695163-3d7fc9bc-4777-4e0f-9bdf-a9a9bb2258e6.png)

### What browsers are you seeing the problem on?

Firefox

### Additional context

Firefox v100, Manjaro Linux

**Comment by LadnerJonas** [comment] 2022-05-22 14:05
My stylesheet was still in the cache. After clearing the cache, the text is white again. If this is planned behavior, the issue can be closed.

**Comment by julian-christl** [comment] 2022-05-23 18:09
Please confirm that you can switch back and forth without getting the above-mentioned issue again.

**Comment by LadnerJonas** [comment] 2022-05-23 18:20
I am not 100% sure if switch back and forth on the exercise page would have solved the bug. But I am sure was re-opening the exercise multiple times. A shift+reload (reload without cache on firefox) solved the issue several minutes later.

**Comment by julian-christl** [comment] 2022-05-23 18:35
I'm not asking whether this would have solved the issue (if it's because of the caching, it wouldn't have), but whether you can reproduce the issue now after clearing the cache when switching back and forth.

**Comment by LadnerJonas** [comment] 2022-05-23 18:50
No, I cannot reproduce the issue with disabled cache. But I also cannot switch between Artemis Versions, which, in my opinion, most likely caused this issue.

**Comment by julian-christl** [comment] 2022-05-23 18:59
With caching such an issue can occur for various reasons, e.g. if the cache gets corrupted.
As it works right now and it's not reproducible by switching back and forth between the modes, the most likely reason would be a caching issue.

I, therefore, close this issue as already suggested. In case this occurs again, feel free to reopen this with more information or write another issue.

**Closed by julian-christl** 2022-05-23 18:59 UTC
Labels: bug
