### ISSUE TITLE
`Assessment`: Tutor note input field available if not submission is selected

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#9203] opened 2024-08-09 11:08 UTC
### Describe the bug

The input field for the tutor note is displayed, even if no submission is available anymore.

### To Reproduce

1. Create an exercise and participate
2. Set the due date to now
3. Assess the submission of the exercise
4. Click on `Assess next`
5. See that the input field for the tutor note is displayed and errors in the console are displayed as the note is not linked to a submission

### Expected behavior

The input field should not be displayed if no submission is available anymore.

### Screenshots

![displaysNoteIfNoSubmissionIsAvailable](https://github.com/user-attachments/assets/ad5b8446-93ee-4c3e-9a68-fa2db51be832)

### Which version of Artemis are you seeing the problem on?

7.5.0

### What browsers are you seeing the problem on?

Chrome

**Comment by Strohgelaender** [comment] 2024-08-09 12:07
duplicate of #9164

**Closed by Strohgelaender** 2024-08-09 12:07 UTC
Labels: bug, good first issue, client, priority:low
