### ISSUE TITLE
Set seconds of dates per default to '00' (so time should be 'XX:XX:00')

### ISSUE THREAD

**Issue by philgabr** [ls1intum/Artemis#2422] opened 2020-11-17 17:15 UTC
### Is your feature request related to a problem?

When creating exercises or exams you need to specify a lot of dates (e.g. visibility/start/end/assessment/due-date). Therefore you only have the date + the time in hours and minutes as input. Seconds then get set automatically with the seconds from the current time. This is a bit annoying, as in most cases seconds should just equal '00' (e.g. exam starting/ending times should be precise to prevent any complaints by students) and therefore need to be changed manually afterwards.

### Describe the solution you'd like

When dates are determined for exercises/exams, the resp. seconds should just be set to '00' per default, as this would be the required value for appr. 99% of the cases.

### Describe alternatives you've considered

An alternative would be to change the input field so that you could also define the seconds directly when determining the date. 
From my perspective the other solution (seconds = '00' per default) would be better and way less effort.

### Additional context

dates in exercise creation (the seconds would need to be changed manually 3x):
![image](https://user-images.githubusercontent.com/73602874/99420519-94031900-28fd-11eb-8e93-74be35bb50a7.png)

dates in exercise creation (the seconds would need to be changed manually 6x):
![image](https://user-images.githubusercontent.com/73602874/99420980-2c010280-28fe-11eb-8650-b9b2b5c42511.png)

input field for dates (seconds cannot be defined):
![image](https://user-images.githubusercontent.com/73602874/99423114-869b5e00-2900-11eb-9be2-eff03dc8a232.png)

**Comment by krusche** [comment] 2020-11-20 19:52
Duplicate of #1649

**Closed** 2020-11-20 19:52 UTC
Labels: feature
