### ISSUE TITLE
`Programming exercises`: Instructor assignment repository cannot be created

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#6812] opened 2023-07-03 07:17 UTC
### Describe the bug

As instructor, creating the assignment repository is not possible. An access forbidden error is thrown.

### To Reproduce

1. Edit in Editor for a programming exercise.
2. Click on ‘Create Assignment Repository’.
3. Access Forbidden, repository is not created.

Possibly only an issue after the exercise due date.

### Expected behavior

The repository is created.

### Which version of Artemis are you seeing the problem on?

6.3.1, 6.3.2

### What browsers are you seeing the problem on?

Firefox

### Additional context

The called endpoint is `api/exercises/:exerciseId/participations`

### Relevant log output

```shell
2023-07-03 07:13:48.347  WARN 1 --- [nio-8080-exec-9] o.z.problem.spring.common.AdviceTraits   : Forbidden: Not allowed
```

**Comment by krusche** [comment] 2023-07-03 21:48
Duplicate of #6430

**Closed by krusche** 2023-07-03 21:48 UTC
Labels: bug, component:Programming
