### ISSUE TITLE
Wrong solution leads to cryptic error message

### ISSUE THREAD

**Issue by JoejoeSt** [ls1intum/Artemis#860] opened 2019-09-27 08:50 UTC
### Describe the bug
I created an exercise and only edited the tests and made a submission as a student. But I left the solution unchanged. The resulting error message was: "opt/bamboobuildagent/bamboo-agent-home/xml-data/build-dir/PGDPTESTJBA-GE25CUS-JOB1" (ge25cus is my Tum login). This could be a bit more clearer...

#### To Reproduce
1. Create new Exercise and only edit the tests
2. Leave the solution as it is with the strategy pattern template
3. Make a submission
4. Get the error

#### Expected behavior
A better error message or even Artemis giving correct feedback even if the solution is not correct.

### Environment
Shouldn't matter since this is on Artemis side

**Comment by JoejoeSt** [comment] 2019-09-27 09:55
<img width="1792" alt="Bildschirmfoto 2019-09-27 um 11 54 49" src="https://user-images.githubusercontent.com/38322605/65760611-9f095180-e11d-11e9-875c-681d48eb135d.png">
This is from the first error message with "build failed" as clickable text.

**Comment by thilo-behnke** [comment] 2019-09-27 18:29
I think this issue is related to https://github.com/ls1intum/Artemis/issues/861:
The test repository could not compile, so the build failed before running the student's code. It will be hard for us to catch this when the build fails, so we should improve the tooling for writing tests or include an additional check for the test repository to check that it builds.

**Comment by thilo-behnke** [comment] 2019-09-28 14:08
@JoejoeSt Does my explanation solve the issue for you? I have created a follow up feature request on Artemis that could ease the debugging process in future: https://github.com/ls1intum/Artemis/issues/868

**Comment by thilo-behnke** [comment] 2019-09-30 09:23
I'm closing this now as it is not a bug, but a workflow issue.

**Comment by krusche** [comment] 2019-09-30 09:36
If the build fails, the user should see the errors of the build log. I just looked into the build log and see the following:


[ERROR] COMPILATION ERROR :
--
27-Sep-2019 09:06:44 | [INFO] -------------------------------------------------------------
27-Sep-2019 09:06:44 | [ERROR] /opt/bamboobuildagent/bamboo-agent-home/xml-data/build-dir/PGDPTESTJBA2-GE25CUS-JOB1/behavior/test/in/tum/de/JBATest.java:[27,9] cannot find symbol
27-Sep-2019 09:06:44 | symbol:   method assertFalse(java.lang.String,boolean)
27-Sep-2019 09:06:44 | location: class in.tum.de.JBATest

We should investigate why this build log is not shown to the user in this particular case.

So I would like to reopen this issue and investigate this

**Comment by thilo-behnke** [comment] 2019-09-30 18:51
> If the build fails, the user should see the errors of the build log. I just looked into the build log and see the following:
> 
> ## [ERROR] COMPILATION ERROR :
> 27-Sep-2019 09:06:44 | [INFO] -------------------------------------------------------------
> 27-Sep-2019 09:06:44 | [ERROR] /opt/bamboobuildagent/bamboo-agent-home/xml-data/build-dir/PGDPTESTJBA2-GE25CUS-JOB1/behavior/test/in/tum/de/JBATest.java:[27,9] cannot find symbol
> 27-Sep-2019 09:06:44 | symbol:   method assertFalse(java.lang.String,boolean)
> 27-Sep-2019 09:06:44 | location: class in.tum.de.JBATest
> 
> We should investigate why this build log is not shown to the user in this particular case.
> 
> So I would like to reopen this issue and investigate this

You are right, that is strange. I tried to reproduce it, e.g. in a sequential test run exercise with a compile error in the behavior tests, but I was not able to.

**Closed** 2019-12-14 20:33 UTC
Labels: bug
