### ISSUE TITLE
Integrate tests into repo downloads

### ISSUE THREAD

**Issue by Isigiel** [ls1intum/Artemis#1130] opened 2019-12-09 15:41 UTC
### Is your feature request related to a problem?

When grading programming exercises I always have to copy a studentes exercide into my test folder in order to locally run the tests on that execise ans clean the folder after I'm done.

### Describe the solution you'd like

It would be exceptionally cool if artemis would optionally do that for me when downloading repos, so that I could just import all the projects into my IDE and wouldn't be bothered with setup work anymore.

### Describe alternatives you've considered

Writing my own scripts/tools that would help me, but those thoughts morphed into an artemis clone pretty quickly.

### Additional context

While thinking about this it seemed to me as if artemis could use some segmentation. For example writing a toool based on the artemis api just for grading prgramming exercises seems very doable for me, but it would probably be a nightmare integrating it into artemis.

**Comment by krusche** [comment] 2019-12-11 11:11
I like this idea, great suggestion. We will add an option for this in the future.

**Comment by krusche** [comment] 2019-12-14 22:49
Just found out that this is a duplicate of https://github.com/ls1intum/Artemis/issues/863
Let's discuss the feature request in the original issue and I close this one

**Closed by krusche** 2019-12-14 22:49 UTC
Labels: component:Programming, feature
