### ISSUE TITLE
[Exam] [Investigation] Short answer and drag and drop quizzes not properly saved

### ISSUE THREAD

**Issue by kloessst** [ls1intum/Artemis#1963] opened 2020-07-24 09:47 UTC
### Describe the bug
For one tester, the short answer and drag and drop quizzes were not properly saved.

#### To Reproduce
Need to investigate if this is reproducible or an user error

#### Expected behavior
All kinds of quizzes are saved properly

**Comment by julian-christl** [comment] 2020-07-24 19:45
Tested with @tessaRuckstuhl, @fde312 and @anditurdiu. We couldn't reproduce this issue.

**Comment by krusche** [comment] 2020-07-25 07:28
Not reproducible, so we close it

**Closed by krusche** 2020-07-25 07:28 UTC
Labels: bug, component:Quiz, exam mode, priority:critical
