### ISSUE TITLE
Behavior tests aren't executed

### ISSUE THREAD

**Issue by JoejoeSt** [ls1intum/Artemis#861] opened 2019-09-27 10:03 UTC
### Describe the bug
We are currently preparing the PGdP course and are creating some test exercises. 
Two exercises have the same Problem:
Even though there is a behavior test it isn't executed and the feedback is "1 of 1 passed".
Sadly we don't have a clue how this is caused or can be reproduced since these are the only two exercises that have the problem and they don't differ from our other exercises.

#### To Reproduce
If this is possible for you, you could look at the exercise "Johannes Breaks Artemis 2" in the course "Praktikum Grundlagen der Programmierung (Test)".
If this isn't possible I provided the three repositories for tests, the solution an my submission.
[JBA2.zip](https://github.com/ls1intum/Artemis/files/3662165/JBA2.zip)

**Comment by thilo-behnke** [comment] 2019-09-27 17:41
Hi @JoejoeSt, I don't have access to the course by I try to help anyway.

When I open test only behavior test file `JBATest.java` I see the following code:

```
package in.tum.de;

import static org.junit.Assert.*;

import org.junit.Test;

/**
 * @author Stephan Krusche (krusche@in.tum.de)
 * @version 3.0 (25.09.2019)
 */
public class JBATest extends BehaviorTest {
    private JBA jba;

    @Before
    public void setup() {
        jba = new JBA();
    }

    @Test
    public void testGetCurrentFolder() {
        assertEquals(jba.getCurrentFolder(), "42", jba.getCurrentFolder()));
    }
}
```
I see two issues in the code:
- line 27 has one closing bracket too much in the end
- The import for `import org.junit.Before;` is missing

I found these issues by first copying the solution repository into the test repository folder, then renaming the solution repository to assignment, and finally executing `mvn clean test` in the behavior folder.

This is the corrected JBATest file:

```
package in.tum.de;

import static org.junit.Assert.*;

import org.junit.Test;
import org.junit.Before;

/**
 * @author Stephan Krusche (krusche@in.tum.de)
 * @version 3.0 (25.09.2019)
 */
public class JBATest extends BehaviorTest {
    private JBA jba;

    @Before
    public void setup() {
        jba = new JBA();
    }

    @Test
    public void testGetCurrentFolder() {
        assertEquals(jba.getCurrentFolder(), "42", jba.getCurrentFolder());
    }
}
```

**Comment by thilo-behnke** [comment] 2019-09-27 17:47
In cases like this the information about the behavioral test gets lost because the Bamboo job fails (the test could not be executed due to a compile error). We might want to improve this in future, but the current way is to verify that the test repository is compiling in a local IDE.

The "Edit in Editor" interface in the Course Administration might help to fiddle around with the code if smaller changes need to be made:

![image](https://user-images.githubusercontent.com/28230611/65790235-7efa8200-e15f-11e9-992f-b7c7494a50a7.png)

**Comment by thilo-behnke** [comment] 2019-09-28 14:07
@JoejoeSt Does my explanation solve the issue for you? I have created a follow up feature request on Artemis that could ease the debugging process in future: https://github.com/ls1intum/Artemis/issues/863

**Comment by thilo-behnke** [comment] 2019-09-30 09:23
I'm closing this now as it is not a bug, but a workflow issue.

**Closed by thilo-behnke** 2019-09-30 09:23 UTC
Labels: bug
