### ISSUE TITLE
Handling of "no submission left" for file upload exercises

### ISSUE THREAD

**Issue by philgabr** [ls1intum/Artemis#2998] opened 2021-03-10 18:05 UTC
### Is your feature request related to a problem?

When assessing file upload exercise submissions in exams, and there is no submission left but one clicks on "assess next submission", only an empty page is displayed.

### Describe the solution you'd like

Ideally there would be an information "all submissions have been graded" and a button that takes you back to the assessment dashboard of the respective exam.

### Describe alternatives you've considered

Alternatively, an error message like "no submission left" would already be better than the current solution. However, to provide consistency with text exercises, the above descried solution would be better. 

### Additional context

![image](https://user-images.githubusercontent.com/73602874/110675611-5f301000-81d3-11eb-8841-de848aa389d4.png)

**Comment by FrankeLukas** [comment] 2021-03-11 13:17
I already added a fix for this in #2994.

**Comment by Strohgelaender** [comment] 2021-03-11 13:46
potential duplicate of #2702

**Closed** 2021-03-15 11:07 UTC
Labels: exam mode, feature, priority:low
