### ISSUE TITLE
Exception occurs only on assignment repositories not on sample solution (identical code)

### ISSUE THREAD

**Issue by LordMuetze** [ls1intum/Artemis#6201] opened 2023-02-03 09:48 UTC
### Describe the bug

When running the tests on the sample solution locally on my machine or online by Artemis they run flawlessly und reach 100%.
When the tests are run on my students or even my assignment repository I get the exception from the section log output (even the code is 100% identical to the solution):

Testwise code coverage is turned on.

### To Reproduce

[I have instructor rights in the course]
1. On a new programming exercise with Maven turn on testwise code coverage.
3. (minimal) Code of the solution:
```
package src.x10wdh01;
import java.util.Scanner;

public class Hauptklasse
{    static public void eingabe()
    {
        Scanner sc =  new  Scanner(System.in);
        String eingabe = sc.nextLine();
        System.out.println("Du hast den Text '" + eingabe + "' eingegeben.");
        
        int zahl = 0;
        /// TASK: Nutzereingabe als Zahl einlesen und in Variable zahl speichern
        zahl = sc.nextInt();

        /// Ein paar Sachen zur Überprüfung berechnen und ausgeben
        System.out.print("Das Quadrat der Zahl ist ");
        System.out.print(zahl * zahl);
        System.out.print(", ihre Gegenzahl ist ");
        System.out.println( - zahl);
    }
}
```

4. (minimal) Code of the tests:
```
package src.x10wdh01;
import [...]
@Public
@WhitelistPath("target")
@BlacklistPath("target/test-classes")

class TestEingabe
{
    private ByteArrayOutputStream outContent;
    private PrintStream originalOut;
    private String out;

    private ByteArrayInputStream inContent;
    private InputStream originalIn;
    List<String> errMsgBuilder;

    @BeforeEach
    public void beforeEach() throws ClassNotFoundException
    {
        outContent = new ByteArrayOutputStream();
        inContent = new ByteArrayInputStream(("eingabe"+System.lineSeparator()+"5").getBytes());

        originalOut = System.out;
        originalIn = System.in;
        System.setOut(new PrintStream(outContent));
        System.setIn(inContent);

        runMethodUnderTest();


        errMsgBuilder = new LinkedList<>();
    }

    @AfterEach
    public void afterEach()
    {
        // reset
        System.setOut(originalOut);
        System.setIn(originalIn);

        if(errMsgBuilder.size()>0)
        {
            fail(String.join("\n",errMsgBuilder));
        }
    }

    void runMethodUnderTest() throws ClassNotFoundException
    {
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        Class<?> myClass = Class.forName("src.x10wdh01.Hauptklasse");
        invokeMethod(myClass, getMethod(myClass, "eingabe"));

        out = outContent.toString();
    }
        @Test
    public void A5_Eingabe()
    {
        String[] lines = Arrays.stream(out.split(System.lineSeparator())).filter(x->!x.equals("")).toArray(String[]::new);
        String[] expected = new String[] {
                "Du hast den Text 'eingabe' eingegeben.",
                "Das Quadrat der Zahl ist 25, ihre Gegenzahl ist -5"
        };


        if(lines.length != expected.length)
        {
            errMsgBuilder.add("Deine Ausgabe enthält die falsche Anzahl an Zeilen. Erwartet: "+ expected.length +
                    " Zeilen. Deine Ausgabe enthält " + lines.length+ " Zeilen.");
        }

        for(int i=0; i < lines.length && i < expected.length; i++)
        {
            if(lines[i].equals("Das Quadrat der Zahl ist 0, ihre Gegenzahl ist 0"))
            {
                errMsgBuilder.add("Dein Programm hat scheinbar Probleme beim Einlesen der Eingabe. Die Variable eingabe hat den Standardwert 0.");
            }
            else if(!lines[i].equals(expected[i]))
            {
                errMsgBuilder.add("Dein Programm gibt einen falschen Text aus: '"+ lines[i] +"'");

            }
        }
        if(errMsgBuilder.size()>0)
        {
            fail(String.join("\n",errMsgBuilder));
        }
    }
}

```

### Expected behavior

Not getting the described exception.

### Which version of Artemis are you seeing the problem on?

6.0.1

### What browsers are you seeing the problem on?

Chrome

### Additional context

As I'm a high school teacher my students use BlueJ as IDE. Therefore I had to adjust the package of my classes by adding the src folder to the package structure.
--> instead of "package x10wdh01;" my first line in every file is now "package src.x10wdh01;".
The folder structure has not been changed.

### Relevant log output

```shell
org.opentest4j.AssertionFailedError: Could not invoke the method 'eingabe' in the class Hauptklasse because of an exception within the method: java.util.ServiceConfigurationError: Locale provider adapter "CLDR"cannot be instantiated.
	at src.x10wdh01.TestEingabe.runMethodUnderTest(TestEingabe.java:75)
	at src.x10wdh01.TestEingabe.beforeEach(TestEingabe.java:50)
```

**Comment by simon-hng** [comment] 2023-02-03 10:57
This seems to be a configuration error in bluej. Is there some way to add `/src` to the source folders. It seems bluej thinks that the root is the src folder

**Comment by MaisiKoleni** [comment] 2023-02-03 17:21
This is related [Ares](https://github.com/ls1intum/Ares/) and the problem is that Scanner requires access to the locale when it is first initialized. One way this can probably be worked around is by using `Scanner` in the test code, e.g. in `@BeforeAll`.
It would be nice to solve this in Ares such that these workarounds are not needed, but it might not always work due to misalignment of the Ares security design with the standard JDK security design and static initializations.

**Comment by b-fein** [comment] 2023-02-03 17:23
I checked and can confirm that by adding
```java
    @BeforeAll
    public static void init() {
        Scanner sc = new Scanner(System.in);
    }
```
to the test class the issue no longer occurs.

**Comment by MaisiKoleni** [comment] 2023-02-03 17:24
Please don't hesitate to open a bug in the Ares repository again if the workaround is too problematic for you or you would really like a better solution. I would recommend closing the issue here, though, as it does not depend on Artemis but only on Ares.

**Closed** 2023-02-03 17:25 UTC
Labels: bug

**Comment by b-fein** [comment] 2023-02-03 17:33
Some additional context how we located the issue to make debugging easier if a similar issue occurs again:

In the build log of the CI system there were two lines
```
NWSFs ==> [src.x10wdh01.Hauptklasse.eingabe(Hauptklasse.java:7)]
BAD PACKAGE ACCESS: sun.util.locale.provider (BL:false, WL:false)
```
The first one gives a location where the disallowed access to a forbidden package happened, and then you get more information which package was accessed.
Usually, this can be fixed by allowing the respective package with a `@WhitelistPackage(...)` annotation to the test class (except for the two special cases `jdk.internal`, `sun`, and their sub-packages).
