### ISSUE TITLE
`Programming exercises`: The status message does not disappear when importing a programming exercise 

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#8033] opened 2024-02-14 13:45 UTC
### Describe the bug

The status message does not disappear when importing a programming exercise. Even pressing X (close). 

### To Reproduce

1. Import a programming exercise and verify that the status message does not disappear when importing a programming exercise. Even pressing X (close). 
2. The same occurs when updating the exercise.

See screenshots below. 

### Expected behavior

The status message should disappear (after some seconds) when importing a programming exercise. Also when pressing X (close). 

### Screenshots

<img width="741" alt="Screenshot 2024-02-14 at 14 42 17" src="https://github.com/ls1intum/Artemis/assets/88991954/5a8e5034-1c69-4692-ae11-ec6ae604a818">

<img width="677" alt="image" src="https://github.com/ls1intum/Artemis/assets/88991954/aa99b685-8843-4e27-a929-e4d63f89a04f">

### Which version of Artemis are you seeing the problem on?

6.8.0

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by milljoniaer** [comment] 2024-02-14 15:58
This is caused by a type error which partially breaks the detail-page of programming exercises. It will be fixed with the above linked PR.

**Closed** 2024-02-14 17:36 UTC
Labels: bug, component:Programming
