### ISSUE TITLE
`Exercise's view`: The buttons are not adapted to the same size. 

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#7887] opened 2024-01-15 08:48 UTC
### Describe the bug

Just the Iris button has a correct height  

<img width="641" alt="image" src="https://github.com/ls1intum/Artemis/assets/88991954/6c9748df-8b07-4811-a0cb-63f3ed4cdc06">

### To Reproduce

1. Go to any programming exercise as an isntructor and check that you can see the same as the screenshot! 

### Expected behavior

all buttons should keep the same height. None of them are double-line

### Screenshots

<img width="684" alt="image" src="https://github.com/ls1intum/Artemis/assets/88991954/1d3abd56-923a-4eaa-892b-465b34aea55e">

### Which version of Artemis are you seeing the problem on?

6.7.5

### What browsers are you seeing the problem on?

Chrome

**Comment by Hialus** [comment] 2024-01-15 09:13
Duplicate of #7879.

**Closed by Hialus** 2024-01-15 09:13 UTC
Labels: bug
