### ISSUE TITLE
Back Button in Team Exercises not working

### ISSUE THREAD

**Issue by Alexanderkrp** [ls1intum/Artemis#1645] opened 2020-06-14 14:02 UTC
#### To Reproduce

1. Go to any Team Exercise
2. Click on the Exercise
3. Try to navigate to the previous site by using the back button

#### Screenshots
![ezgif com-crop](https://user-images.githubusercontent.com/52030186/84593166-1701de00-ae4b-11ea-991d-df478b7163c6.gif)

**Comment by MaisiKoleni** [comment] 2020-06-18 23:44
I was not able to reproduce this, neither from the Tutor Dashboard nor from the Course Management Exercise List. The button always works for me (using a Chromium-based Browser on Win 10).
Could you please provide a more detailed sequence of steps to reproduce and provide details about your system/environment? Are there other conditions that are required for the bug to appear?

**Comment by tiffca** [comment] 2020-11-14 10:53
I'm also not able to reproduce this, hence closing.
I'm able to assess team exercises and navigate back using the back button.

**Closed by tiffca** 2020-11-14 10:53 UTC
Labels: bug, more-info-needed
