### ISSUE TITLE
Announcements emails are send twice to tutors/editors

### ISSUE THREAD

**Issue by fh314** [ls1intum/Artemis#5348] opened 2022-07-08 11:24 UTC
### Describe the bug

As an editor of the EIST courses, I always receive the announcements emails twice. 

### Expected behavior

Only send announcement emails once to editors/tutors

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment] 2022-07-08 16:41
I think this happens because we have two courses with similar announcements, one for Garching and one for Heilbronn.
Did you double check that you received the exact same email with the same course name?

**Comment by fh314** [comment] 2022-07-12 17:14
Yes, I did get two emails for Heilbronn and Garching each
![image](https://user-images.githubusercontent.com/29736922/178552029-c99dd782-c788-48bd-b97e-1ac69bdb32c5.png)

**Comment by krusche** [comment] 2022-07-13 05:04
Are you maybe listed twice in the course? For example as tutor and as editor?

**Comment by krusche** [comment] 2022-07-13 18:39
We should definitely fix it and take a set-based union of all students, tutors, editors and instructors of the course before sending the emails to avoid potential duplicates. Should be relatively easy to implement if someone finds the corresponding source code

**Comment by ge65cer** [comment] 2022-10-18 18:10
Duplicate of https://github.com/ls1intum/Artemis/issues/5246

**Closed by ge65cer** 2022-10-18 18:10 UTC
Labels: bug, component:Notification, email
