### ISSUE TITLE
Please let me remove courses manually

### ISSUE THREAD

**Issue by Matthias878** [ls1intum/Artemis#4995] opened 2022-04-29 13:16 UTC
### Describe the solution you'd like

A button somewhere, maybe with a "Are you sure?" Question, that let's me remove courses

**Comment by ge65cer** [comment] 2022-05-01 17:57
Duplicate of #334?

**Closed** 2022-05-03 17:09 UTC
Labels: duplicate, feature

**Comment by Matthias878** [comment] 2022-10-11 07:37
Yes correct sorry
Moritz Aberle ***@***.***> schrieb am Di., 3. Mai 2022, 19:09:
