### ISSUE TITLE
Leave Courses

### ISSUE THREAD

**Issue by lukas-rapp** [ls1intum/Artemis#5013] opened 2022-05-03 14:57 UTC
### Is your feature request related to a problem?

I'm always frustrated when I see the Artemis Tutorial Course. Why isn't there a way to leave the course? We need a way to do that.

### Describe the solution you'd like

Add a "leave course" button at least for the test course

**Comment by ge65cer** [comment] 2022-05-03 17:08
Duplicate of #334

**Closed by ge65cer** 2022-05-03 17:08 UTC
Labels: duplicate, feature
