### ISSUE TITLE
Students can continue working on an exam in a 2nd browser window if they have already handed in early in the 1st browser window

### ISSUE THREAD

**Issue by csarpkaya** [ls1intum/Artemis#1903] opened 2020-07-17 12:25 UTC
### Describe the bug

If the exam is opened on two browsers simultaneously, it's possible to hand in one early (e.g. on Chrome) and get a PDF export and then edit the exam again on the other browser (e.g. Firefox). It's not allowed to hand in the exam early again, however after the deadline the exam is saved and it's possible to get to different PDF exports with different answers for the same student & exam.  I'm also guessing the latter submission is saved for the actual assessment.

#### To Reproduce

1. Start an already created & started exam on two different browsers as the same student.
2. Answer the questions on one browser and hand in the exam early. Get directed to the exam summary page.
3. Answer questions on the other browser differently, try to hand in it early, it shouldn't work.
4. After the deadline passes refresh the page, you should again be redirected to the exam summary page.
5. You should be able to see two different summaries & exports available for the same student on two different browsers.

#### Expected behavior
After an exam is handed in early making a change on it shouldn't be possible even on a different browser. The answers that are saved for the assessment should be the ones that were handed in first.

#### Screenshots

![image](https://user-images.githubusercontent.com/64203961/87785922-b860c300-c841-11ea-9c40-1a05d6064cc8.png)

### Environment
<details><pre>
 - Chrome, Firefox
</pre></details>

**Comment by Varnika-Tyagi** [comment] 2020-07-17 12:48
The issue is that the student can still work on the exam in a different browser even after handing it in early in one browser, as long as he doesn't reload the page.
The student, then, gets these two different summaries. If you refresh the 'old' summary, it changes to the newer version as well, thereby reflecting the changes the student made after handing the exam in early.

**Comment by krusche** [comment] 2020-07-17 12:50
Thanks for finding this issue, we will fix it!

**Comment by krusche** [comment] 2020-07-18 21:07
fixed by an additional check that saving the submissions is not possible any more if the student exam was handed in early

**Closed by krusche** 2020-07-18 21:07 UTC
Labels: bug, exam mode, priority:critical
