### ISSUE TITLE
`Programming exercises`: Diff is not working

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#8027] opened 2024-02-13 09:14 UTC
### Describe the bug

The diff is not working in programming exercises. 

### To Reproduce

Open any programming exercise and click in the 'show' button to see the diff between the template end the solution. 

### Expected behavior

Should show the diff. 

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/88991954/dc7c543c-c0b7-4e91-8fe9-1ddc8a084f51)

<img width="877" alt="image" src="https://github.com/ls1intum/Artemis/assets/88991954/c8bb2b88-15ae-4eac-825e-7a5680760077">

### Which version of Artemis are you seeing the problem on?

6.8.0

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by krusche** [comment] 2024-02-14 15:42
Does this really happen for all programming exercises or only for specific ones?

**Comment by milljoniaer** [comment] 2024-02-14 15:59
This is caused by a Type error which partially breaks the detail page of programming exercises. It will be fixed with the above linked PR.

**Closed** 2024-02-14 17:36 UTC
Labels: bug, component:Programming, priority:high
