### ISSUE TITLE
Missing results of solution participation

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#3786] opened 2021-07-16 18:13 UTC
### Describe the bug

The results of the solution for programming exercises is not correctly shown in Artemis.
When taking a look at Bamboo, the builds run fine, but they are apparently not correctly detected or imported by Artemis.

### To Reproduce

1. Create a programming exercise
2. Change some code in either the solution or the tests ~(you might have to do this a couple of times, it does not fail every time)~
    a) change the solution
    b) immediately change the tests
    c) immediately change the solution (tests have to be building)
3. Go to the results of the solution
4. See empty results

### Expected behavior

Artemis should correctly import the results from Bamboo

### Screenshots

Artemis result view:
![Participations](https://user-images.githubusercontent.com/38322605/125991142-ec2c44ba-428d-451c-9b31-c7ca8de06b14.png)
Commits of solution:
![Bildschirmfoto 2021-07-16 um 17 11 46](https://user-images.githubusercontent.com/38322605/125991136-1f2ec9ed-91a5-4f99-b1cd-c909f41645c2.png)
Commits of tests:
![TestsHashes](https://user-images.githubusercontent.com/38322605/125991141-7a2d7346-080a-4035-8058-cba54699294a.png)

### What browsers are you seeing the problem on?

Safari

**Comment by krusche** [comment] 2021-07-16 22:04
The issue might be related to the fact that Bamboo reports multiple commits (from the `assignment` and `tests` repo). When Artemis receives the result, it tries to map it to an existing submission, which seems to fail for some reason in some cases.

**Comment by julian-christl** [comment] 2021-07-18 12:25
In our case, this was resolved when renaming the test methods so that they were globally unique.
So I think this was an issue with the duplicated names because I never experienced that problem anymore after that.

**Comment by dfuchss** [comment] 2021-07-19 12:46
It's also the case for Jenkins instances.
But at least results were handled by the backend `The new result for *********-SOLUTION was saved successfully`

**Comment by MaisiKoleni** [comment] 2021-07-27 14:10
We were unable to find any behavior were results got lost or not displayed. It seems that Bamboo cancels builds that are triggered in short succession. But Artemis always creates a submission for each test and solution commit, and that seems to work reliably. Due to the merged/aborted builds, no build result is available for the corresponding Artemis submission (the number of builds in Artemis corresponds to the number of builds in Bamboo). In such cases, it makes sense to have no results for a submission.

Please close this issue or specify how we can reproduce a loss of information or other errors. Are special settings needed?

**Closed** 2021-07-27 14:20 UTC
Labels: bug, more-info-needed, needs specification
