### ISSUE TITLE
Display of drag-and-drop exercises can be glitchy

### ISSUE THREAD

**Issue by JonasSC** [ls1intum/Artemis#1910] opened 2020-07-17 14:10 UTC
### Describe the bug
In drag-and-drop exercises, the drag-and-drop fields can be misaligned with the background image. This affects both the exercise itself and its display at the summary page.
Usually, zooming in or out, as well as resizing the browser window can fix this issue. Sometimes, this even fixes the issue at the original zoom level and window size. In this case, reloading the page will revert to the glitchy state.

#### To Reproduce
1. Create an exam with a drag-and-drop exercise
2. Work on the exercise and check for issues
3. Finish the exam and check for issues on the summary page

It is unknown how to reproduce the glitches reliably. Try zooming in and out, when it does not occur. Also, relatively large background images seem to be more prone to cause the glitch.

#### Expected behavior
The positions and sizes of the drag-and-drop fields should always be aligned properly with the background image, irrespective of the zoom level or the window size.

#### Screenshots
This shows the glitch during the exercise. Don't worry about the header and the footer overlapping the display of the exercise. This is because the browser rendered the whole page for the screenshot and not just the displayed area.
![Screenshot_2020-07-17 Exam(1) Kopie](https://user-images.githubusercontent.com/2746810/87795133-e812c980-c847-11ea-9659-dfa0c52ee95d.png)

This shows the glitch in the summary page.
![Screenshot_2020-07-17 Exam(2) Kopie](https://user-images.githubusercontent.com/2746810/87795147-ecd77d80-c847-11ea-8d0a-05e9ec39dd12.png)

### Environment
Firefox on MacOS
Chrome on Windows

**Comment by krusche** [comment] 2020-07-17 17:57
Might be related or a duplicate of #1795

**Closed** 2020-07-19 06:04 UTC
Labels: bug, priority:critical
