### ISSUE TITLE
H04E04 disappearing connections 

### ISSUE THREAD

**Issue by ge49tuf** [ls1intum/Artemis#1558] opened 2020-06-03 10:16 UTC
### Describe the bug
When I submitted the H04E04 homework all the connections between interfaces and components were visible, but now after deadline when I checked how my answer looks like I cannot see most of those connections, they disappeared for me.

#### To Reproduce
I cannot give clear steps on how to reproduce this error since it happened after the submission deadline, and before that everything worked as usual.

#### Expected behavior
All modeled connections visible.

#### Screenshots

This is how it looks for me now: 
![Screenshot (153)](https://user-images.githubusercontent.com/66033809/83624880-7e8a7480-a593-11ea-950d-6b5f72faf05e.png)

before all those interfaces were connected to components
### Environment
 - OS: Windows10
 - Browser: Chrome Version 83.0.4103.61

**Comment by jpbernius** [comment] 2020-06-03 10:46
Thank you for reporting this issue @ge49tuf. Given your description, I would close this as a duplicate of #1556 which should be fixed by #1557.

**Closed by jpbernius** 2020-06-03 10:46 UTC
Labels: bug
