### ISSUE TITLE
Visual bug with exam overlay

### ISSUE THREAD

**Issue by FlorianStang** [ls1intum/Artemis#2788] opened 2021-01-30 17:58 UTC
### Describe the bug
When clicking on the logged in user during an exam the drop-down menu is overlapped by the exam timer overlay.

#### To Reproduce

1. Participate in an exam
2. Click on your username

#### Expected behavior
Drop-down menu is behind the exam timer

#### Screenshots

![grafik](https://user-images.githubusercontent.com/73840724/106364114-01cfb600-632d-11eb-981c-d4a4d57c3b5c.png)

**Comment by Strohgelaender** [comment] 2021-01-30 21:33
Duplicate of #2727

**Closed** 2021-02-01 10:29 UTC
Labels: bug, exam mode
