### ISSUE TITLE
Badge or tag for submitted exercises.

### ISSUE THREAD

**Issue by truongvu3** [ls1intum/Artemis#485] opened 2019-05-23 09:21 UTC
### Describe the solution you'd like
 I would like the tasks to be labeled with tags once I have submitted them in order to know which one I have already submitted and which one I have not.

**Comment by rjrj98** [comment] 2019-05-23 17:24
Yeah it would maybe be cool if hole task changed its color when submitted

**Comment by jpbernius** [comment] 2019-09-04 22:13
I am closing this as a duplicate of #427.

**Closed by jpbernius** 2019-09-04 22:13 UTC
Labels: duplicate, feature
