### ISSUE TITLE
I have an idea for statistics. Create a pie chart for percentage of submitted exercises near to current chart, so that students can see, how many percent they achieved in the exercises which they have already done. 🚀 

### ISSUE THREAD

**Issue by gabitii** [ls1intum/Artemis#459] opened 2019-05-16 08:20 UTC

**Comment by MaisiKoleni** [comment] 2019-05-27 11:21
I guess by submitted you mean submitted *and* graded. I agree with you, think this would make the chart much more useful. But correct me if I am wrong, this is pretty much the same problem as stated here, isn't it?
Duplicate of #411

**Comment by gabitii** [comment] 2019-05-29 16:19
Yes, I meant that exactly the problem described in #411.

**Comment by maximilianmeier** [comment] 2019-06-23 14:05
In #590 we changed how the score is calculated. We only include exercise with a due date in the past. With the improved statistics it should be more clear how the score is calculated and what exercises are included. Please check the tooltips of each exercise to get more information

**Closed by maximilianmeier** 2019-06-23 14:05 UTC
Labels: feature
