### ISSUE TITLE
No AI reporting after several times

### ISSUE THREAD

**Issue by Yunxuan13** [ls1intum/Artemis#9556] opened 2024-10-21 19:23 UTC
### Describe the bug

After 3 or 4 submissions and asking for feedback from AI, it shows me "This submission already has an existing AI result. Please submit again before requesting further feedback."

### To Reproduce

1. Go to Exercise W01E01 Strategy vs. bridge pattern
2. Click on Request AI feedback
4. See error :This submission already has an existing AI result. Please submit again before requesting further feedback.

### Expected behavior

It can provide me a response after I submitted and asking for AI feedback.

### Which version of Artemis are you seeing the problem on?

7.6.1

### What browsers are you seeing the problem on?

Safari

**Comment by maximiliansoelch** [comment] 2024-10-22 12:55
Duplicate of #9550

**Closed by maximiliansoelch** 2024-10-22 12:55 UTC
Labels: bug, assessment, exercise, iris, programming, text
