### ISSUE TITLE
Class disappearing behind package after submitting

### ISSUE THREAD

**Issue by timmatejek** [ls1intum/ArTEMiS#482] opened 2019-05-23 07:45 UTC
### Describe the bug
In lecture 05 the in-class task was modeling classes in packages. I did so and everything was displayed correctly during modeling and after saving. Yet, after submitting one class suddenly disappeared but the association was still visible pointing into nowhere.

#### To Reproduce

1. Model a package with one class on it
2. save and submit
3. view the submitted model and eventually see the bug

#### Expected behavior
The class should be displayed infront of the package and not disappear probably behind it.

#### Screenshots
[Screenshot.pdf](https://github.com/ls1intum/ArTEMiS/files/3210818/Screenshot.pdf)

### Environment

<details><pre>
 - Windows 10 home
 - Chrome
</pre></details>

#### Additional context
none

#### Output in Web Console

<details><pre>
  none
</pre></details>

**Comment by jwilland-tum** [comment] 2019-05-24 10:41
Thanks for your time to report this issue! As this is a duplicate of https://github.com/ls1intum/ArTEMiS/issues/479 I will close this issue. Any further discussion regarding this issue should be done in the linked issue.

**Closed by jwilland-tum** 2019-05-24 10:41 UTC
Labels: bug

**Comment by jwilland-tum** [comment] 2019-05-24 10:42
Duplicate of #479
