### ISSUE TITLE
Drag and Drop areas in Quiz Exercises are not displayed correctly

### ISSUE THREAD

**Issue by FrankeLukas** [ls1intum/Artemis#3752] opened 2021-07-13 16:57 UTC
### Describe the bug

When I create a drag and drop question for quiz exercises I defined an area for a drag item like this:
![grafik](https://user-images.githubusercontent.com/72132281/125493910-0ff76234-e0ee-4c43-b53f-a9ba7b184d7a.png)

But when viewing the quiz (in preview mode) the area looks like this:
![grafik](https://user-images.githubusercontent.com/72132281/125493947-8bfeb32f-cb36-4afd-bea1-1cc6d7eca637.png)

Also see https://github.com/ls1intum/Artemis/pull/3741#pullrequestreview-705433668.

### To Reproduce

1. Create a new quiz exercise and add a drag and drop question
2. Create an area for a drop item (drag onto the uploaded image)
3. Save the quiz
3. Preview the quiz from the exercises lsit

### Expected behavior

The area should be roughly in the same in edit and (pre)view modes.

### What browsers are you seeing the problem on?

Firefox

**Comment by Olimbia23** [comment] 2021-07-13 19:57
@FrankeLukas 
I can not reproduce the issue. It looks fine to me as shown in the video below:

https://user-images.githubusercontent.com/51077603/125516710-f2194db9-433e-4d0f-9d13-3cb160a1c321.mov

**Comment by FrankeLukas** [comment] 2021-07-13 20:00
My bad, I didn't specify that I mean the preview when you already saved the exercise and click on "Preview" from the exercises list.

**Comment by Olimbia23** [comment] 2021-07-15 01:21
It seems like the issue appears to be related with wrong calculation of area of the drag-and-drop-element. 
As we can see from the video, for small background images if the size is specified as a square (not how it looks like in the edit screen, but rather based on values), then so it is in the preview (as shown in the video)
https://user-images.githubusercontent.com/51077603/125711795-558477ff-cb2e-4868-bc42-234d068cf812.mov

However, even though area is calculated wrongly for big images as well, they seem to be rendered correctly in the preview, weird :\

A lot of logic is done in these methods:
- https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/exercises/quiz/manage/drag-and-drop-question/drag-and-drop-question-edit.component.ts#L200-L251
- https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/exercises/quiz/manage/drag-and-drop-question/drag-and-drop-question-edit.component.ts#L362-L401

Maybe if we could somehow remove the logic based on the backgroundSize (since the issue is happening for the small images, guess it's the root cause).
BTW do you know what this `200` stands for in the code? 🤔

**Comment by julian-christl** [comment] 2021-07-15 11:02
As described here: https://github.com/ls1intum/Artemis/pull/3616/files
In the quiz-exercise-generator.ts, the 200 appears to be the maximum size. It appears that the magic numbers were not removed in the drag-and-drop-question-edit.component.ts

**Comment by krusche** [comment] 2021-07-16 08:59
200=2*100 (so it's double the resolution of 100%). It has been used to improve the possibility to choose the position of drop zones.
I would appreciate a quick bugfix to this issue, so that we can use those questions reliably.

**Comment by MerlinMehmed** [comment] 2021-09-29 16:02
The bug was fixed with [[Bugfix] quiz drag-and-drop-question-edit #3789](https://github.com/ls1intum/Artemis/pull/3789). I also tested it and couldn't reproduce it. Can we close it @krusche?

**Comment by julian-christl** [comment] 2021-09-30 00:33
Since #3789 directly referenced this issue and Stephan merged it himself, we can close it. 
I think the closing reference is broken like that. It would have to be something like `Fixes #1234` or `Closes #1234` but not `Fix for issue #1234` (cc @Olimbia23 in case you didn't realise yet :D)

Therefore I'll close it even though my name is not Stephan Krusche 👀

**Closed by julian-christl** 2021-09-30 00:33 UTC
Labels: bug
