### ISSUE TITLE
Exercise indicator doesn't turn yellow on unsaved changes (text, programming)

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1737] opened 2020-06-29 08:36 UTC
### Describe the bug
If you edit a text or programming exercise the exercise indicator at the top doesn't turn yellow like it should on unsaved changes.

#### To Reproduce
1. Edit an text and programming exercise in the exam
2. Indicator doesn't turn yellow

#### Expected behavior
Indicator turns yellow and blue when saved

#### Screenshots
Didn't made a screenshot during the test exam but I think it's pretty straight forward.

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome v83.0.4103.116
</pre></details>

**Comment by stefanwaldhauser** [comment] 2020-06-30 14:42
This is currently intended behaviour as far as I understand. Only when the connection is lost it will turn yellow.

**Comment by julian-christl** [comment] 2020-06-30 14:53
Then this is bad design in my opinion since the user should know all the time what is saved an what not to see one a problem araises with saving.

What are your thoughts on this @filip-gregurevic as Dev Lead, @Varnika-Tyagi as Test Lead

**Comment by krusche** [comment] 2020-07-03 07:03
should be fixed now

**Closed by krusche** 2020-07-03 07:03 UTC
Labels: bug, exam mode, exam mode: client
