### ISSUE TITLE
Possible problems when using ID for equals and hashcode in domain classes

### ISSUE THREAD

**Issue by stefanwaldhauser** [ls1intum/Artemis#2171] opened 2020-10-07 10:01 UTC
### Describe the bug

Currently we are using the database id for equals and hashcode of entities (see `DomainObject`). This is generally considered not ideal: https://docs.jboss.org/hibernate/core/4.0/manual/en-US/html/persistent-classes.html#persistent-classes-equalshashcode

The problem is also discussed here:
https://youtu.be/EZwpOLCfuq4?t=2059
https://stackoverflow.com/questions/5031614/the-jpa-hashcode-equals-dilemma

## Example Problem
A good example problem is described here : "https://developer.jboss.org/docs/DOC-13933"

`// Suppose UserManager and User are Beans mapped with Hibernate
UserManager u = session.load(UserManager.class, id);
u.getUserSet().add(new User("newUsername1")); // adds a new Entity with id = null or id = 0
u.getUserSet().add(new User("newUsername2")); // has id=null, too so overwrites last added object.
// u.getUserSet() now contains only the second User`

##### Solution 1: Rewrite `equals` and `hashcode` for our domain entities by using business keys
The combination of both fields just has to be stable enough for the life duration of the Set.
For example, if you have an "Item" class and it has a "name" String and "created" Date, I can use both to implement a good equals() method.

- Advantage: No DB changes necessary
- Disadvantage: A lot of files need changes

##### Solution 2: Generate a unique business key using the superclass for all entities
![image](https://user-images.githubusercontent.com/29718932/95317460-833e9c80-0895-11eb-96e7-2b32d0bb815b.png)

The solution is also described here: https://youtu.be/EZwpOLCfuq4?t=2197
- Advantage: Only one file needs to be changed
- Disadvantage: DB changes necessary for new uuid field

**Comment by MaisiKoleni** [comment] 2020-10-07 14:03
While I think we need to be careful here, I do think that this is not that much of a problem.

One major difference that is not taken into account in the issue is that we explicitly _do not_ consider two objects equal if the id of one or both is `null`.

`hashCode` could be a problem, but I cannot think of any place where we create a set containing not-persisted objects and continue to use this set after persisting the object, making it a set of objects that had no id when added, and objects that had one.
At least in the code I have seen, we only use the objects returned by a JPA `save` and not continue using the ones passed to the method. I this is the case, we might need to change that.

Of course, this problem could theoretically still appear, and if we want to solve it, I would go with solution 2 or a mix of both. Using only solution 1 could be really problematic, because many of our objects don't offer a good natural key. 
Either way, I would suggest being very careful and considerate what we do here.

We should analyse where this issue actually affects our code and then check how it can/should be solved.

**Comment by krusche** [comment] 2020-10-14 22:07
Closing this issue for now as we are not really affected.
We should add this to our server coding guidelines though!

**Closed by krusche** 2020-10-14 22:07 UTC
Labels: bug
