### ISSUE TITLE
Reply button as an Instructor

### ISSUE THREAD

**Issue by mhunter02** [ls1intum/Artemis#9862] opened 2024-11-25 21:07 UTC
### Describe the bug

In an exercise view (not communication panel), when someone replied to a message and I click on a reply (as an instructor role) I get to edit this message, rather than replying to it.

### To Reproduce

1. Go to 'Exercise'
2. Click on 'Reply button on an already replied message'
4. See edit of this reply.
<img width="346" alt="image" src="https://github.com/user-attachments/assets/1600a97e-b360-4eab-bddb-c1711e1e564a">

### Expected behavior

I reply to the reply

### Screenshots

<img width="378" alt="image" src="https://github.com/user-attachments/assets/ce69764e-2f77-4aad-bca2-db9796411fe5">
<img width="392" alt="Screenshot 2024-11-25 at 22 05 34" src="https://github.com/user-attachments/assets/3baf28c4-315c-4db5-bcff-98e99cf26120">
**This is not me, this is a student**
<img width="345" alt="image" src="https://github.com/user-attachments/assets/e71a846b-4fe4-4769-9273-5e29c442b426">

### Which version of Artemis are you seeing the problem on?

7.7.1

### What browsers are you seeing the problem on?

Chrome

### Additional context

It is okay in the Communication page

<img width="1233" alt="image" src="https://github.com/user-attachments/assets/9ad0e049-ffc7-476a-ae6f-03244416d7b3">

**Comment by badkeyy** [comment] 2024-11-27 13:15
Can't reproduce in 7.7.3 --> There is no reply button for a reply: 
![image](https://github.com/user-attachments/assets/21f70322-f0a9-4ac0-98f7-f22da0967154)

**Comment by asliayk** [comment] 2024-11-27 21:12
this is fixed by this PR https://github.com/ls1intum/Artemis/pull/9815

**Closed by asliayk** 2024-11-27 21:12 UTC
Labels: bug, communication, exercise, lecture
